"""French Flet desktop interface for Arty Frame Studio.

The host schedules commands over USB/UART. All waveform edges are generated by
the FPGA; the host application never attempts to bit-bang GPIO pins.
"""

from __future__ import annotations

import asyncio
import math
import os
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Any

import flet as ft  # type: ignore[import-untyped]
import flet.canvas as cv  # type: ignore[import-untyped]

from .bitstream import read_bitstream
from .firmware_config import (
    DRIVES_MA,
    PMOD_PINS,
    SLEWS,
    FirmwareBuildConfig,
    pll_settings,
)
from .model import (
    CONTINUOUS,
    REFERENCE_HZ,
    FrameConfig,
    divider_for_frequency,
    free_clock_ticks,
    load_profile,
    parse_word,
    save_profile,
    ticks_for_ns,
)
from .prebuilt import validate_programming_image
from .protocol import DeviceStatus, FirmwareInfo, Opcode
from .remote_build import GitHubBuildClient, RemoteBuildTarget
from .simulation import Waveform, export_csv, export_vcd, simulate, waveform_svg
from .toolchain import Toolchain, ToolchainConfig
from .transport import CommandTimeout, DemoDevice, SerialDevice, list_ports, run_led_test
from .ui_layout import (
    AMBER,
    BG,
    BLUE,
    GREEN,
    LED_OFF,
    LED_ON,
    LINE,
    MUTED,
    PANEL,
    RED,
    TEXT,
    build_layout,
)
from .windows_jtag import probe_arty, program_arty

CHART_HEIGHT = 332
SIGNALS = (("DATA", "data", "#2563EB"), ("CLK", "clk", "#B45309"), ("LATCH", "latch", "#9333EA"))


def ticks_from_ns(value: str, *, allow_zero: bool = False, core_hz: int = REFERENCE_HZ) -> int:
    """Round a finite nonnegative duration to the firmware's half-core-cycle grid."""
    try:
        ns = float(value.strip().replace(",", "."))
    except ValueError as exc:
        raise ValueError("La durée doit être un nombre en nanosecondes.") from exc
    return ticks_for_ns(ns, allow_zero=allow_zero, core_hz=core_hz)


def core_clock_options() -> list[Any]:
    return [
        ft.dropdown.Option(
            str(setting.core_hz),
            f"{setting.core_hz / 1e6:g} MHz · pas {setting.tick_ns:.4g} ns",
        )
        for setting in pll_settings()
    ]


def pin_options() -> list[Any]:
    return [
        ft.dropdown.Option(
            name,
            f"{name} · {pin.package_pin}"
            + (" · 200 Ω" if not pin.high_speed else f" · paire {pin.pair}"),
        )
        for name, pin in PMOD_PINS.items()
    ]


def firmware_missing(info: FirmwareInfo) -> str:
    """Première fonction absente d'un firmware ancien, à signaler à l'utilisateur."""
    for present, label in (
        (info.led_test, "sans test LED"),
        (info.continuous, "sans émission continue"),
        (info.free_clock, "sans CLK libre"),
    ):
        if not present:
            return f" · {label} : recharger le firmware fourni à jour"
    return ""


def format_duration(ns: float) -> str:
    if math.isinf(ns):
        return "illimitée (jusqu'à Arrêter)"
    if ns >= 1e9:
        return f"{ns / 1e9:.4g} s"
    if ns >= 1e6:
        return f"{ns / 1e6:.4g} ms"
    if ns >= 1e3:
        return f"{ns / 1e3:.4g} µs"
    return f"{ns:.4g} ns"


def waveform_signal_points(
    waveform: Waveform, signal: str, width: float
) -> list[tuple[float, float]]:
    """Exact digital steps for one trace, scaled to the available canvas width."""
    if signal not in ("data", "clk", "latch"):
        raise ValueError("Signal inconnu.")
    if not math.isfinite(width) or width < 200:
        raise ValueError("Largeur du chronogramme insuffisante.")
    row = ("data", "clk", "latch").index(signal)
    high, low = 84.0 + row * 64, 114.0 + row * 64
    left, right = 92.0, width - 28

    def position(ticks: int) -> float:
        return left + ticks / waveform.duration_ticks * (right - left)

    first = waveform.transitions[0]
    previous = high if getattr(first, signal) else low
    points = [(position(first.time_ticks), previous)]
    for transition in waveform.transitions[1:]:
        x = position(transition.time_ticks)
        level = high if getattr(transition, signal) else low
        points.append((x, previous))
        if level != previous:
            points.append((x, level))
        previous = level
    if points[-1][0] < right:
        points.append((right, previous))
    if len(points) > 4 * (right - left):
        return _thin_points(points)
    return points


def _thin_points(points: list[tuple[float, float]]) -> list[tuple[float, float]]:
    """Dense CLK libre : par colonne de pixel, niveau d'entrée, trait vertical, sortie."""
    thinned: list[tuple[float, float]] = []
    index = 0
    while index < len(points):
        column = float(round(points[index][0]))
        first = last = points[index][1]
        other: float | None = None
        index += 1
        while index < len(points) and float(round(points[index][0])) == column:
            level = points[index][1]
            if level != first:
                other = level
            last = level
            index += 1
        thinned.append((column, first))
        if other is not None:
            thinned.append((column, other))
            if last == first:
                thinned.append((column, first))
    return thinned


def waveform_canvas_shapes(waveform: Waveform, width: float = 1200) -> list[Any]:
    """Render traces and text natively; SVG remains an independent export format."""
    left, right = 92.0, width - 28
    shapes: list[Any] = [
        cv.Rect(0, 0, width, CHART_HEIGHT, border_radius=12, paint=ft.Paint(color="#F8FAFC")),
        cv.Text(
            22,
            14,
            "Chronogramme numérique idéal",
            style=ft.TextStyle(size=16, color="#0F172A", weight=ft.FontWeight.W_700),
        ),
        cv.Text(
            22,
            40,
            f"{waveform.config.bit_count} bits · "
            f"{waveform.config.frequency_hz / 1e6:.6g} MHz · "
            f"{'LSB' if waveform.config.lsb_first else 'MSB'} en premier",
            style=ft.TextStyle(size=12, color="#475569"),
        ),
    ]
    grid_paint = ft.Paint(
        color="#E2E8F0", stroke_width=1, style=ft.PaintingStyle.STROKE, stroke_dash_pattern=[3, 4]
    )
    unit, scale = ("µs", 1000) if waveform.duration_ns >= 1000 else ("ns", 1)
    for index in range(11):
        x = left + index / 10 * (right - left)
        shapes.extend(
            [
                cv.Line(x, 70, x, 260, paint=grid_paint),
                cv.Text(
                    x,
                    270,
                    f"{waveform.duration_ns * index / 10 / scale:.3g}",
                    alignment=ft.alignment.top_center,
                    style=ft.TextStyle(size=10, color="#475569"),
                ),
            ]
        )
    for row, (label, signal, color) in enumerate(SIGNALS):
        points = waveform_signal_points(waveform, signal, width)
        shapes.append(
            cv.Text(
                20,
                91 + row * 64,
                label,
                style=ft.TextStyle(size=13, color=color, weight=ft.FontWeight.W_700),
            )
        )
        elements = [cv.Path.MoveTo(*points[0])]
        elements.extend(cv.Path.LineTo(*point) for point in points[1:])
        shapes.append(
            cv.Path(
                elements=elements,
                paint=ft.Paint(color=color, stroke_width=2, style=ft.PaintingStyle.STROKE),
                data=f"signal:{signal}",
            )
        )
    bit_width = 2 * waveform.config.divider / waveform.duration_ticks * (right - left)
    if bit_width >= 14:
        for index, bit in enumerate(waveform.config.bits):
            sample_tick = (2 * index + 1) * waveform.config.divider
            x = left + sample_tick / waveform.duration_ticks * (right - left)
            shapes.append(
                cv.Text(
                    x,
                    126,
                    str(bit),
                    alignment=ft.alignment.center,
                    style=ft.TextStyle(size=10, color="#2563EB"),
                )
            )
    shapes.append(
        cv.Text(
            22,
            305,
            f"Temps ({unit}) · Échantillonnage DATA au front montant de CLK",
            style=ft.TextStyle(size=11, color="#475569"),
        )
    )
    return shapes


def project_directory() -> Path:
    configured = os.environ.get("ARTY_FRAME_PROJECT")
    if configured:
        return Path(configured).expanduser().resolve()
    if (Path.cwd() / "firmware").is_dir():
        return Path.cwd()
    return Path(__file__).resolve().parents[2]


class Studio:
    """Own controls, connection lifecycle and asynchronous background work."""

    tabs: ft.Tabs
    setup_steps: ft.Container
    tool_panel: ft.Container

    def __init__(self, page: ft.Page, project_root: Path | None = None) -> None:
        self.page = page
        self.project_root = project_root or project_directory()
        self.device: SerialDevice | DemoDevice | None = None
        self.device_status: DeviceStatus | None = None
        self.serial_lock = asyncio.Lock()
        self.serial_pending = False
        self.tool_pending = False
        self.programming_pending = False
        self.is_windows = os.name == "nt"
        self.closing = False
        self.poll_task: asyncio.Task[Any] | None = None
        self.current_config: FrameConfig | None = None
        self.waveform: Waveform | None = None
        self.last_sent: FrameConfig | None = None
        self.command_uncertain = False
        # Horloge du firmware visé : lue par INFO une fois connecté, choisie
        # dans l'interface pour la démo et la simulation.
        self.core_hz = REFERENCE_HZ
        self.firmware_info: FirmwareInfo | None = None
        self.known_firmwares = {0: FirmwareBuildConfig()}
        self.browse_target: ft.TextField | None = None
        self.led_step = 0.25
        self.previous_base = "hex"
        self.loop: asyncio.AbstractEventLoop | None = None
        self.worker_messages: list[str] = []
        self.log_flush_handle: asyncio.TimerHandle | None = None
        self.chart_width = 1200.0
        self._create_controls()

    def _field(
        self,
        label: str,
        value: str,
        *,
        width: int = 180,
        on_change: Callable[..., Any] | None = None,
        helper: str | None = None,
    ) -> ft.TextField:
        return ft.TextField(
            label=label,
            value=value,
            width=width,
            dense=True,
            border_color=LINE,
            focused_border_color=AMBER,
            text_style=ft.TextStyle(color=TEXT),
            helper_text=helper,
            on_change=on_change or self._changed,
        )

    def _card(self, *controls: ft.Control) -> ft.Container:
        return ft.Container(
            content=ft.Column(
                list(controls), spacing=15, horizontal_alignment=ft.CrossAxisAlignment.STRETCH
            ),
            bgcolor=PANEL,
            border=ft.border.all(1, LINE),
            border_radius=16,
            padding=20,
        )

    @staticmethod
    def _heading(title: str, subtitle: str | None = None) -> ft.Control:
        controls: list[ft.Control] = [ft.Text(title, size=18, weight=ft.FontWeight.W_600)]
        if subtitle:
            controls.append(ft.Text(subtitle, size=12, color=MUTED))
        return ft.Column(controls, spacing=4)

    def _create_controls(self) -> None:
        self.mode = ft.Dropdown(
            label="Connexion",
            value="demo",
            width=210,
            options=[
                ft.dropdown.Option("demo", "Démo locale"),
                ft.dropdown.Option("uart", "Carte · USB / UART"),
            ],
            on_change=self._mode_changed,
        )
        self.port = ft.Dropdown(label="Port série", width=280, disabled=True, options=[])
        self.refresh_button = ft.IconButton(
            icon=ft.Icons.REFRESH,
            tooltip="Actualiser les ports série",
            on_click=self._refresh_ports,
        )
        self.connect_button = ft.ElevatedButton(
            "Connecter",
            icon=ft.Icons.USB,
            on_click=self._toggle_connection,
        )
        self.connection_status = ft.Text("Déconnecté", color=MUTED)
        self.mode_badge = ft.Text("Simulation", size=12, color=BLUE)
        self.connection_hint = ft.Text(size=12, color=MUTED)
        self.hardware_pinout = ft.Text(size=12, color=BLUE, selectable=True)
        self.prepare_button = ft.TextButton(
            "Préparer la carte", icon=ft.Icons.MEMORY, on_click=self._open_fpga
        )
        self.hardware_status = ft.Text("Aucune émission", size=12, color=MUTED)
        self.firmware_status = ft.Text("Firmware non identifié", size=12, color=MUTED)
        self.led_test_button = ft.OutlinedButton(
            "Tester les LED",
            icon=ft.Icons.LIGHTBULB_OUTLINE,
            tooltip="Chenillard sur LD4-LD7 : chaque motif est une commande confirmée",
            on_click=self._led_test,
            disabled=True,
        )
        self.led_lamps = [
            ft.Container(width=16, height=16, border_radius=8, bgcolor=LED_OFF) for _ in range(4)
        ]
        self.led_note = ft.Text(size=11, color=MUTED)
        self.word = self._field("Valeur de la trame", "2AAAAAA", width=340)
        self.word.text_style = ft.TextStyle(font_family="monospace", color=TEXT)
        self.base = ft.Dropdown(
            label="Notation",
            value="hex",
            width=180,
            options=[
                ft.dropdown.Option("bin", "Binaire"),
                ft.dropdown.Option("hex", "Hexadécimal"),
                ft.dropdown.Option("dec", "Décimal"),
            ],
            on_change=self._base_changed,
        )
        self.bit_count = self._field("Nombre de bits", "26", width=145, helper="1 à 26 bits")
        self.core_clock = ft.Dropdown(
            label="Horloge du cœur FPGA",
            value=str(REFERENCE_HZ),
            width=230,
            options=core_clock_options(),
            on_change=self._core_changed,
        )
        self.frequency = self._field(
            "Fréquence demandée (MHz)",
            "10",
            width=215,
            on_change=self._frequency_changed,
            helper="Cœur / N",
        )
        self.divider = self._field(
            "Diviseur N",
            "20",
            width=145,
            on_change=self._divider_changed,
            helper="Entier de 1 à 65 535",
        )
        self.latch_ns = self._field("Impulsion LATCH (ns)", "20", width=205)
        self.gap_ns = self._field("Pause après LATCH (ns)", "100", width=205)
        self.repeat = self._field("Répétitions", "1", width=145, helper="1 à 65 535 trames")
        # CLK libre : CLK garde sa période pendant LATCH et la pause ; ces
        # durées sont alors arrondies à des périodes entières (révision 4).
        self.free_clock = ft.Switch(
            label="CLK libre (continue pendant LATCH et pause)",
            value=False,
            on_change=self._changed,
            tooltip=(
                "CLK ne s'interrompt plus ; LATCH et pause sont arrondis à des périodes "
                "entières de CLK, DATA et LATCH changent aux fronts descendants"
            ),
        )
        # Émission continue : SEND avec repeat_count 0, la carte répète la
        # trame jusqu'à STOP (firmware révision 3).
        self.continuous = ft.Switch(
            label="Émission continue jusqu'à Arrêter",
            value=False,
            on_change=self._continuous_changed,
            tooltip="CLK, DATA et LATCH se répètent sans fin ; le bouton Arrêter les termine",
        )
        self.lsb = ft.Switch(label="LSB en premier", value=False, on_change=self._changed)
        self.latch_low = ft.Switch(label="LATCH actif bas", value=False, on_change=self._changed)
        self.frequency_actual = ft.Text(size=19, color=AMBER, weight=ft.FontWeight.W_600)
        self.timing_summary = ft.Text(color=MUTED, size=12)
        self.quantization_note = ft.Text(size=12, color=MUTED)
        self.binary_preview = ft.Text(size=19, color=BLUE, selectable=True, font_family="monospace")
        self.order_preview = ft.Text(size=12, color=MUTED, selectable=True)
        self.validation = ft.Text(size=12, color=RED)
        self.send_button = ft.ElevatedButton(
            "Envoyer la trame",
            icon=ft.Icons.PLAY_ARROW,
            on_click=self._send,
            disabled=True,
            style=ft.ButtonStyle(bgcolor=AMBER, color=BG),
        )
        self.stop_button = ft.OutlinedButton(
            "Arrêter",
            icon=ft.Icons.STOP,
            on_click=self._stop,
            disabled=True,
        )
        self.simulate_button = ft.OutlinedButton(
            "Actualiser le chronogramme",
            icon=ft.Icons.SHOW_CHART,
            on_click=self._simulate_clicked,
        )
        self.profile_path = self._field(
            "Fichier de profil JSON",
            str(self.project_root / "profiles" / "default.json"),
            width=600,
            on_change=lambda _: None,
        )
        self.profile_message = ft.Text(size=12, color=MUTED)
        self.wave_canvas = cv.Canvas(
            shapes=[],
            width=1200,
            height=CHART_HEIGHT,
            on_resize=self._chart_resized,
            resize_interval=100,
            visible=False,
        )
        self.wave_note = ft.Text(size=12, color=MUTED)
        self.export_path = self._field(
            "Chemin des exports (extension remplacée selon le format)",
            str(self.project_root / "exports" / "chronogramme"),
            width=650,
            on_change=lambda _: None,
        )
        self.export_message = ft.Text(size=12, color=MUTED, selectable=True)
        self.toolchain_path = self._field(
            "Configuration de la chaîne open source (JSON)",
            str(self.project_root / "toolchain.json"),
            width=650,
            on_change=lambda _: None,
        )
        self.bitstream_path = self._field(
            "Bitstream validé de ce projet (.bit)",
            str(self.project_root / "build" / "arty_frame.bit"),
            width=650,
            on_change=lambda _: None,
        )
        self.doctor_button = ft.OutlinedButton(
            "Vérifier les outils",
            icon=ft.Icons.FACT_CHECK,
            on_click=self._doctor,
        )
        self.build_button = ft.ElevatedButton(
            "Compiler localement",
            icon=ft.Icons.BUILD,
            on_click=self._build,
        )
        self.program_button = ft.ElevatedButton(
            "Programmer la SRAM",
            icon=ft.Icons.MEMORY,
            on_click=self._program,
            style=ft.ButtonStyle(bgcolor=AMBER, color=BG),
        )
        reference = FirmwareBuildConfig()
        self.fw_core = ft.Dropdown(
            label="Horloge du cœur",
            value=str(reference.core_hz),
            width=230,
            options=core_clock_options(),
            on_change=self._firmware_changed,
        )
        self.fw_pins = {
            field: ft.Dropdown(
                label=label,
                value=getattr(reference, field),
                width=200,
                options=pin_options(),
                on_change=self._firmware_changed,
            )
            for field, label in (
                ("data_pin", "Broche DATA"),
                ("clock_pin", "Broche CLK"),
                ("latch_pin", "Broche LATCH"),
            )
        }
        self.fw_drive = ft.Dropdown(
            label="Courant",
            value=str(reference.drive_ma),
            width=120,
            options=[ft.dropdown.Option(str(value), f"{value} mA") for value in DRIVES_MA],
            on_change=self._firmware_changed,
        )
        self.fw_slew = ft.Dropdown(
            label="Fronts",
            value=reference.slew,
            width=120,
            options=[ft.dropdown.Option(value) for value in SLEWS],
            on_change=self._firmware_changed,
        )
        self.fw_summary = ft.Text(size=12, color=BLUE, selectable=True)
        self.fw_warnings = ft.Text(size=12, color=AMBER, selectable=True)
        self.fw_config_path = self._field(
            "Configuration firmware (JSON)",
            str(self.project_root / "profiles" / "firmware.json"),
            width=650,
            on_change=lambda _: None,
        )
        self.gh_repository = self._field(
            "Dépôt GitHub", RemoteBuildTarget().repository, width=300, on_change=lambda _: None
        )
        self.gh_ref = self._field("Branche", "main", width=160, on_change=lambda _: None)
        self.gh_token = ft.TextField(
            label="Jeton GitHub (Actions : lecture et écriture)",
            value=os.environ.get("ARTY_GITHUB_TOKEN", ""),
            password=True,
            can_reveal_password=True,
            width=420,
            dense=True,
            border_color=LINE,
            focused_border_color=AMBER,
            text_style=ft.TextStyle(color=TEXT),
            helper_text="Conservé en mémoire seulement ; envoyé uniquement à api.github.com.",
        )
        self.remote_build_button = ft.ElevatedButton(
            "Compiler sur GitHub",
            icon=ft.Icons.CLOUD_UPLOAD,
            on_click=self._remote_build,
        )
        self.ftdi_dll_path = self._field(
            "DLL FTDI D2XX (facultatif)",
            "",
            width=650,
            on_change=lambda _: None,
            helper="Vide : utilise le pilote FTDI existant, notamment installé avec Adept.",
        )
        self.ftdi_serial = self._field(
            "Série JTAG A (facultatif)",
            "",
            width=300,
            on_change=lambda _: None,
        )
        self.jtag_probe_button = ft.OutlinedButton(
            "Détecter le FPGA sous Windows",
            icon=ft.Icons.USB,
            on_click=self._jtag_probe,
        )
        prebuilt_firmware = self.project_root / "firmware" / "prebuilt" / "arty_frame.bit"
        self.selected_firmware_note = ft.Text(
            "Firmware fourni · cœur 200 MHz · DATA JB1 · CLK JB2 · LATCH JB3",
            size=12,
            color=BLUE,
            selectable=True,
        )
        self.windows_bitstream_path = self._field(
            "Firmware existant pour l'Arty A7-100T (.bit)",
            str(prebuilt_firmware) if prebuilt_firmware.is_file() else "",
            width=650,
            on_change=self._bitstream_changed,
            helper="Chargez le firmware du projet par JTAG avant de connecter le port COM.",
        )
        self.jtag_program_button = ft.ElevatedButton(
            "Charger le .bit sous Windows",
            icon=ft.Icons.MEMORY,
            on_click=self._jtag_program,
            style=ft.ButtonStyle(bgcolor=AMBER, color=BG),
        )
        self.tool_progress = ft.ProgressBar(visible=False, color=AMBER)
        self.tool_message = ft.Text(size=12, color=MUTED, selectable=True)
        self.doctor_results = ft.Column(spacing=5)
        self.journal = ft.ListView(expand=True, spacing=3, auto_scroll=True)
        self.journal_path = self._field(
            "Fichier du journal",
            str(self.project_root / "exports" / "journal.txt"),
            width=650,
            on_change=lambda _: None,
        )
        self.log_lines: list[str] = []
        self.file_picker = ft.FilePicker(on_result=self._file_chosen)
        if hasattr(self.page, "overlay"):
            self.page.overlay.append(self.file_picker)
        self._refresh_firmware_summary()

    def layout(self) -> ft.Control:
        return build_layout(self)

    def _open_fpga(self, _: Any = None) -> None:
        self.tabs.selected_index = 2
        self._update()

    def _open_control(self, _: Any = None) -> None:
        self.tabs.selected_index = 0
        self._update()

    def _browse_path(self, field: ft.TextField, extensions: list[str]) -> None:
        self.browse_target = field
        self.file_picker.pick_files(
            dialog_title="Choisir un fichier",
            file_type=ft.FilePickerFileType.CUSTOM,
            allowed_extensions=extensions,
            allow_multiple=False,
        )

    def _file_chosen(self, event: Any) -> None:
        target = self.browse_target
        self.browse_target = None
        if target is not None and event.files and event.files[0].path:
            target.value = event.files[0].path
            if target is self.windows_bitstream_path:
                self._bitstream_changed()
            self._update()

    def _bitstream_changed(self, _: Any = None) -> None:
        self.selected_firmware_note.value = (
            "Fichier sélectionné · cible et manifeste vérifiés lors du chargement."
        )
        self.selected_firmware_note.color = MUTED
        self._update()

    def _select_firmware(self, path: Path, firmware: FirmwareBuildConfig) -> None:
        self.windows_bitstream_path.value = self.bitstream_path.value = str(path)
        self.known_firmwares[firmware.build_id] = firmware
        self.selected_firmware_note.value = f"Sélectionné · {firmware.summary()}"
        self.selected_firmware_note.color = BLUE

    def _use_reference(self, _: Any = None) -> None:
        self._select_firmware(
            self.project_root / "firmware" / "prebuilt" / "arty_frame.bit", FirmwareBuildConfig()
        )
        self._update()

    def _config(self) -> FrameConfig:
        bits = int(self.bit_count.value or "")
        # The divider is authoritative, while the requested frequency must also
        # remain valid after edits to another field.
        requested_hz = float((self.frequency.value or "").replace(",", ".")) * 1e6
        divider_for_frequency(requested_hz, self.core_hz)
        divider = int(self.divider.value or "")
        if self.free_clock.value:
            # Durées saisies = LATCH et pause visibles, arrondis aux périodes de CLK.
            latch_ticks, gap_ticks = free_clock_ticks(
                float((self.latch_ns.value or "").replace(",", ".")),
                float((self.gap_ns.value or "").replace(",", ".")),
                divider,
                self.core_hz,
            )
        else:
            latch_ticks = ticks_from_ns(self.latch_ns.value or "", core_hz=self.core_hz)
            gap_ticks = ticks_from_ns(
                self.gap_ns.value or "", allow_zero=True, core_hz=self.core_hz
            )
        return FrameConfig(
            word=parse_word(self.word.value or "", self.base.value or "hex", bits),
            bit_count=bits,
            divider=divider,
            latch_ticks=latch_ticks,
            gap_ticks=gap_ticks,
            repeat_count=CONTINUOUS if self.continuous.value else int(self.repeat.value or ""),
            lsb_first=bool(self.lsb.value),
            latch_active_low=bool(self.latch_low.value),
            core_hz=self.core_hz,
            free_clock=bool(self.free_clock.value),
        )

    def _update(self) -> None:
        if not self.closing:
            self.page.update()

    def _chart_resized(self, event: Any) -> None:
        width = float(event.width)
        if not math.isfinite(width) or width < 200 or abs(width - self.chart_width) < 0.5:
            return
        self.chart_width = width
        if self.waveform is not None:
            self.wave_canvas.shapes = waveform_canvas_shapes(self.waveform, width)
            self._update()

    def _changed(self, _: Any = None) -> None:
        self.quantization_note.value = (
            f"Durées arrondies au pas de {1e9 / (2 * self.core_hz):.6g} ns · "
            f"cœur {self.core_hz / 1e6:g} MHz."
        )
        try:
            config = self._config()
            waveform = simulate(config, max_frames=4)
            self.current_config = config
            self.waveform = waveform
            self.wave_canvas.shapes = waveform_canvas_shapes(waveform, self.chart_width)
            self.wave_canvas.visible = True
            self.frequency_actual.value = (
                f"Fréquence réalisée : {config.frequency_hz / 1e6:.7g} MHz · "
                f"{config.core_hz / 1e6:g} MHz / {config.divider}"
            )
            self.binary_preview.value = f"{config.word:0{config.bit_count}b}"
            emitted = (
                self.binary_preview.value[::-1] if config.lsb_first else self.binary_preview.value
            )
            self.order_preview.value = (
                f"Ordre sur DATA → {emitted} · {'LSB' if config.lsb_first else 'MSB'} en premier"
            )
            if config.free_clock:
                latch_text = (
                    f"LATCH {config.latch_periods} période(s) de CLK "
                    f"({config.latch_active_ticks * config.tick_ns:.6g} ns) · "
                    f"Pause {config.gap_periods} période(s) "
                    f"({config.gap_ticks * config.tick_ns:.6g} ns) · CLK continue · "
                )
            else:
                latch_text = (
                    f"LATCH {config.latch_ticks * config.tick_ns:.6g} ns · "
                    f"Pause {config.gap_ticks * config.tick_ns:.6g} ns · "
                )
            self.timing_summary.value = (
                latch_text + f"Période de trame {format_duration(config.frame_duration_ns)} · "
                f"Durée totale {format_duration(config.total_duration_ns)}"
            )
            total = "une émission continue" if config.continuous else str(config.repeat_count)
            self.wave_note.value = (
                f"{waveform.frames_simulated} trame(s) affichée(s) sur {total} · "
                f"fenêtre {format_duration(waveform.duration_ns)} · "
                f"résolution {config.tick_ns:.4g} ns"
                + (" · aperçu limité aux 4 premières trames" if waveform.truncated else "")
            )
            self.validation.value = ""
            self.validation.visible = False
        except (ValueError, TypeError, OverflowError) as exc:
            self.current_config = None
            self.waveform = None
            self.wave_canvas.shapes = []
            self.wave_canvas.visible = False
            self.wave_note.value = "Complétez les paramètres pour afficher le chronogramme."
            self.validation.value = f"Paramètre invalide : {exc}"
            self.validation.visible = True
            self.frequency_actual.value = "Paramètres à corriger"
            self.binary_preview.value = "—"
            self.order_preview.value = ""
            self.timing_summary.value = ""
        self._buttons()
        self._update()

    def _continuous_changed(self, _: Any = None) -> None:
        # Le nombre saisi est conservé pour un retour en émission finie.
        self.repeat.disabled = bool(self.continuous.value)
        self._changed()

    def _frequency_changed(self, _: Any) -> None:
        try:
            hz = float((self.frequency.value or "").replace(",", ".")) * 1e6
            self.divider.value = str(divider_for_frequency(hz, self.core_hz))
        except (ValueError, OverflowError) as exc:
            self.current_config = None
            self.waveform = None
            self.wave_canvas.shapes = []
            self.wave_canvas.visible = False
            self.validation.value = f"Fréquence invalide : {exc}"
            self.validation.visible = True
            self.frequency_actual.value = "Fréquence demandée à corriger"
            self._buttons()
            self._update()
            return
        self._changed()

    def _divider_changed(self, _: Any) -> None:
        try:
            divider = int(self.divider.value or "")
            if divider > 0:
                self.frequency.value = f"{self.core_hz / 1e6 / divider:.9g}"
        except ValueError:
            pass
        self._changed()

    def _core_changed(self, _: Any) -> None:
        try:
            self._apply_core(int(self.core_clock.value or REFERENCE_HZ))
        except ValueError as exc:
            self._error("Horloge du cœur", exc)

    def _apply_core(self, core_hz: int) -> None:
        """Change de base de temps en conservant la fréquence et les durées en ns."""
        self.core_hz = core_hz
        self.core_clock.value = str(core_hz)
        self.divider.helper_text = f"{core_hz / 1e6:g} MHz / N · 1 à 65 535"
        self._frequency_changed(None)

    def _base_changed(self, _: Any) -> None:
        try:
            word = parse_word(
                self.word.value or "", self.previous_base, int(self.bit_count.value or "")
            )
            base = self.base.value
            self.word.value = (
                f"{word:0{int(self.bit_count.value or '')}b}"
                if base == "bin"
                else f"{word:X}"
                if base == "hex"
                else str(word)
            )
        except (ValueError, TypeError):
            pass
        self.previous_base = self.base.value or "hex"
        self._changed()

    def _buttons(self) -> None:
        connected = bool(self.device is not None and self.device.connected)
        busy = bool(self.device_status is not None and self.device_status.busy)
        self.send_button.disabled = (
            not connected
            or self.current_config is None
            or busy
            or self.serial_pending
            or self.programming_pending
            or self.command_uncertain
        )
        self.stop_button.disabled = not connected or self.serial_pending or self.programming_pending
        self.simulate_button.disabled = self.current_config is None
        self.connect_button.disabled = self.serial_pending or self.programming_pending
        self.connect_button.text = "Déconnecter" if connected else "Connecter"
        self.mode.disabled = connected or self.serial_pending or self.programming_pending
        self.port.disabled = (
            connected
            or self.mode.value != "uart"
            or self.serial_pending
            or self.programming_pending
        )
        self.refresh_button.disabled = self.serial_pending or self.programming_pending
        self.port.visible = self.refresh_button.visible = self.mode.value == "uart"
        for control in (
            self.doctor_button,
            self.build_button,
            self.program_button,
            self.jtag_probe_button,
            self.jtag_program_button,
            self.remote_build_button,
        ):
            control.disabled = self.tool_pending
        self.program_button.disabled = self.tool_pending or self.serial_pending
        self.jtag_probe_button.disabled = self.tool_pending or self.serial_pending
        self.jtag_program_button.disabled = self.tool_pending or self.serial_pending
        try:
            self._firmware_settings()
        except ValueError:
            self.build_button.disabled = self.remote_build_button.disabled = True
        led_capable = self.firmware_info is not None and self.firmware_info.led_test
        self.led_test_button.disabled = (
            not connected
            or not led_capable
            or busy
            or self.serial_pending
            or self.programming_pending
        )
        # Une carte connectée impose l'horloge annoncée par son firmware.
        self.core_clock.disabled = connected or self.serial_pending or self.programming_pending
        simulated = self.mode.value == "demo"
        self.core_clock.label = (
            "Horloge démo · déconnecter pour modifier"
            if simulated and connected
            else "Cœur identifié"
            if connected
            else "Horloge de simulation"
        )
        self.prepare_button.visible = not simulated
        self.mode_badge.value = (
            "Simulation · aucun signal physique"
            if simulated
            else ("Carte connectée" if connected else "Carte · déconnectée")
        )
        self.mode_badge.color = BLUE if simulated else GREEN if connected else AMBER
        self.connection_hint.value = (
            "La démo permet de préparer les trames sans carte."
            if simulated
            else "Charger le firmware dans FPGA avant de connecter le port COM à 115 200 bauds."
        )
        self.connection_hint.visible = not connected
        self.hardware_pinout.visible = connected and not simulated
        self.led_test_button.text = "Simuler les LED" if simulated else "Tester les LED"
        self.led_note.value = "Motif simulé" if simulated else "Motif confirmé par UART"
        self.led_test_button.tooltip = (
            "Aperçu local des motifs ; aucune LED physique n'est pilotée"
            if simulated
            else "Chenillard sur LD4–LD7 : chaque motif est une commande confirmée"
        )
        if hasattr(self, "setup_steps"):
            self.setup_steps.visible = not simulated

    def _log(self, message: str, color: str = MUTED) -> None:
        for line in str(message).splitlines():
            stamp = datetime.now().strftime("%H:%M:%S")
            entry = f"{stamp}  {line}"
            self.log_lines.append(entry)
            self.journal.controls.append(
                ft.Text(entry, color=color, size=12, selectable=True, font_family="monospace")
            )
        self.log_lines = self.log_lines[-1000:]
        self.journal.controls = self.journal.controls[-1000:]
        self._update()

    def _error(self, action: str, exc: Exception) -> None:
        message = f"{action} : {exc}"
        self._log(message, RED)
        if not self.closing:
            self.page.open(ft.SnackBar(ft.Text(message), bgcolor="#73353F", duration=8000))

    async def _mode_changed(self, _: Any) -> None:
        self._buttons()
        self._update()

    async def _refresh_ports(self, _: Any = None) -> None:
        try:
            ports = await asyncio.to_thread(list_ports)
            current = self.port.value
            self.port.options = [
                ft.dropdown.Option(p.device, f"{p.device} · {p.description}") for p in ports
            ]
            available = {p.device for p in ports}
            self.port.value = (
                current if current in available else (ports[0].device if ports else None)
            )
            self._log(f"Ports USB/UART détectés : {len(ports)} (firmware non vérifié).")
            for port in ports:
                self._log(f"{port.device} · {port.description} · {port.hwid or 'ID inconnu'}")
            self._update()
        except Exception as exc:
            self._error("Détection des ports", exc)

    async def _toggle_connection(self, _: Any = None) -> None:
        if self.serial_pending or self.programming_pending:
            return
        self.serial_pending = True
        self._buttons()
        self._update()
        try:
            async with self.serial_lock:
                if self.device is not None and self.device.connected:
                    if (
                        isinstance(self.device, SerialDevice)
                        and self.device_status is not None
                        and self.device_status.busy
                    ):
                        # Fermer l'UART n'arrête pas la carte : une émission
                        # continue se poursuit jusqu'à STOP, reset ou coupure.
                        self._log(
                            "La carte poursuit son émission après la déconnexion : "
                            "reconnecter puis Arrêter, ou appuyer sur RESET.",
                            AMBER,
                        )
                    await asyncio.to_thread(self.device.close)
                    self.device = None
                    self.device_status = None
                    self.last_sent = None
                    self._firmware_identified(None)
                    self.connection_status.value = "Déconnecté"
                    self.connection_status.color = MUTED
                    self.hardware_status.value = "Aucune émission"
                    self._log("Connexion fermée.")
                else:
                    device: SerialDevice | DemoDevice
                    if self.mode.value == "uart":
                        if not self.port.value:
                            raise ValueError(
                                "Sélectionnez un port série ou branchez la carte puis actualisez."
                            )
                        device = SerialDevice(self.port.value, baudrate=115200)
                        self._log(f"Identification UART sur {self.port.value} · PING puis INFO.")
                    else:
                        device = DemoDevice(core_hz=self.core_hz)
                    try:
                        status = await asyncio.to_thread(device.connect)
                        # INFO donne l'horloge du cœur ; un firmware de révision 1
                        # répond « commande inconnue » et reste à 200 MHz.
                        info = await asyncio.to_thread(device.identify)
                    except Exception:
                        await asyncio.to_thread(device.close)
                        raise
                    self.device = device
                    self.last_sent = None
                    self.command_uncertain = False
                    self._firmware_identified(info)
                    self._status_received(status)
                    label = (
                        "Démo locale · aucun signal physique"
                        if self.mode.value == "demo"
                        else f"Arty · {self.port.value}"
                    )
                    self.connection_status.value = label
                    self.connection_status.color = GREEN
                    self._log(f"Connecté : {label}.", GREEN)
        except Exception as exc:
            self.device = None
            self.device_status = None
            self.last_sent = None
            self._firmware_identified(None)
            if self.mode.value == "uart":
                self.connection_status.color = RED
                if isinstance(exc, CommandTimeout):
                    if exc.opcode == Opcode.INFO:
                        self.connection_status.value = (
                            f"{self.port.value} · PING reçu, identification INFO incomplète"
                        )
                        self.hardware_status.value = "Vérifier la version du firmware et recharger"
                    else:
                        self.connection_status.value = (
                            f"{self.port.value} ouvert · aucune réponse PING compatible"
                        )
                        self.hardware_status.value = "Vérifier bitstream UART, reset et horloge"
                else:
                    self.connection_status.value = f"Connexion impossible · {self.port.value}"
                    self.hardware_status.value = "Consulter le journal"
            self._error("Connexion", exc)
        finally:
            self.serial_pending = False
            self._buttons()
            self._update()

    def _firmware_identified(self, info: FirmwareInfo | None) -> None:
        self.firmware_info = info
        if info is None:
            self.firmware_status.value = "Firmware non identifié"
            self.firmware_status.color = MUTED
            self.hardware_pinout.value = ""
            self._show_leds(None)
            return
        simulated = self.mode.value == "demo"
        build = "référence" if info.build_id == 0 else f"0x{info.build_id:08X}"
        try:
            local = self._firmware_settings()
        except ValueError:
            local = None
        if local is not None and local.build_id == info.build_id and local.core_hz == info.core_hz:
            self.known_firmwares[info.build_id] = local
        known = self.known_firmwares.get(info.build_id)
        if known is not None and known.core_hz != info.core_hz:
            known = None
        if not simulated and known is not None:
            self.hardware_pinout.value = (
                f"Brochage identifié · DATA {known.data_pin} · CLK {known.clock_pin} · "
                f"LATCH {known.latch_pin} · masse commune"
            )
        elif not simulated:
            self.hardware_pinout.value = (
                "Firmware personnalisé · consulter sa configuration pour le brochage ; "
                "INFO transmet un identifiant, pas les noms des broches."
            )
        prefix = "Firmware simulé" if simulated else "Firmware"
        self.firmware_status.value = (
            f"{prefix} révision {info.revision} · cœur {info.core_hz / 1e6:g} MHz · "
            + ("identité locale" if simulated else f"build {build}")
            + firmware_missing(info)
        )
        complete = info.led_test and info.continuous and info.free_clock
        self.firmware_status.color = GREEN if complete else AMBER
        self._log(self.firmware_status.value, self.firmware_status.color)
        if info.core_hz != self.core_hz:
            self._log(
                f"Base de temps passée à {info.core_hz / 1e6:g} MHz, celle du firmware : "
                "fréquence et durées sont requantifiées.",
                AMBER,
            )
            self._apply_core(info.core_hz)

    def _show_leds(self, pattern: int | None) -> None:
        for index, lamp in enumerate(self.led_lamps):
            lamp.bgcolor = LED_ON if pattern is not None and pattern >> index & 1 else LED_OFF
        self._update()

    def _led_step(self, pattern: int | None) -> None:
        # Appelé depuis le thread du test : l'affichage reste sur la boucle Flet.
        if self.loop is not None and not self.closing:
            self.loop.call_soon_threadsafe(self._show_leds, pattern)
        elif self.loop is None:
            self._show_leds(pattern)

    async def _led_test(self, _: Any = None) -> None:
        if (
            self.serial_pending
            or self.programming_pending
            or (self.device_status is not None and self.device_status.busy)
        ):
            return
        self.serial_pending = True
        self._buttons()
        self._update()
        try:
            async with self.serial_lock:
                device = self.device
                if device is None or not device.connected:
                    raise ValueError("Connectez la carte avant le test LED.")
                self._log(
                    "Simulation LED : aperçu des motifs sans carte."
                    if self.mode.value == "demo"
                    else "Test LED : observer LD4 à LD7 (chenillard, toutes allumées, puis état).",
                    BLUE,
                )
                result = await asyncio.to_thread(
                    run_led_test, device, step=self.led_step, on_step=self._led_step
                )
                message = (
                    f"Test LED terminé · {result.commands} commandes simulées · "
                    "aucun signal physique."
                    if self.mode.value == "demo"
                    else f"Test LED terminé · {result.commands} commandes confirmées · "
                    "aller-retour "
                    f"moyen {result.mean_ms:.1f} ms (max {result.max_ms:.1f} ms). Si les LED "
                    "de la carte n'ont pas défilé, le port répond mais pas cette carte."
                )
                self._log(message, GREEN)
        except Exception as exc:
            self._error("Test LED", exc)
        finally:
            self.serial_pending = False
            self._show_leds(None)
            self._buttons()
            self._update()

    def _status_received(self, status: DeviceStatus) -> None:
        self.device_status = status
        if self.last_sent is not None and self.last_sent.continuous:
            # Le compteur 16 bits de la carte reboucle : il témoigne de
            # l'activité, pas du nombre total de trames depuis SEND.
            self.hardware_status.value = (
                f"Émission continue · compteur {status.completed} (modulo 65 536) · "
                "Arrêter pour terminer"
                if status.busy
                else f"Prêt · émission continue arrêtée · compteur {status.completed}"
            )
        else:
            state = "Émission en cours" if status.busy else "Prêt"
            total = f" / {self.last_sent.repeat_count}" if self.last_sent is not None else ""
            self.hardware_status.value = f"{state} · {status.completed}{total} trame(s) terminée(s)"
        if self.command_uncertain:
            self.hardware_status.value += " · Commande non confirmée : STOP ou reconnexion requis"
        self.hardware_status.color = AMBER if status.busy else MUTED
        self._buttons()

    async def _recover_command_timeout(self, exc: CommandTimeout) -> None:
        """Observe the board without repeating a command that may have run."""
        self.command_uncertain = True
        self.last_sent = None
        self.hardware_status.value = "Commande non confirmée · Lecture de STATUS en cours"
        self._log(
            f"{exc.opcode.name} non confirmé : lecture de STATUS, sans répéter la commande.", AMBER
        )
        try:
            if self.device is None:
                raise ValueError("La carte n'est plus connectée.")
            status = await asyncio.to_thread(self.device.status)
            self._status_received(status)
            self._log(
                f"STATUS observé · busy={int(status.busy)} · "
                f"{status.completed} trame(s) terminée(s). "
                "Ce statut ne prouve pas si la commande sans réponse a été exécutée.",
                AMBER,
            )
        except Exception as status_error:
            self.hardware_status.value = "État inconnu · STOP ou reconnexion requis"
            self._log(f"Lecture de STATUS impossible : {status_error}", RED)

    async def _send(self, _: Any) -> None:
        if self.serial_pending or self.programming_pending or self.command_uncertain:
            return
        try:
            config = self._config()
        except (ValueError, TypeError, OverflowError) as exc:
            self._error("Envoi impossible", exc)
            return
        self.serial_pending = True
        self._buttons()
        self._update()
        try:
            async with self.serial_lock:
                if self.device is None or not self.device.connected:
                    raise ValueError("Connectez la carte ou le mode démo avant l'envoi.")
                try:
                    status = await asyncio.to_thread(self.device.send, config)
                except CommandTimeout as exc:
                    await self._recover_command_timeout(exc)
                    raise
                self.last_sent = config
                self._status_received(status)
                repetitions = (
                    "émission continue jusqu'à Arrêter"
                    if config.continuous
                    else f"{config.repeat_count} répétition(s)"
                )
                self._log(
                    f"SEND · {config.bit_count} bits · 0x{config.word:X} · "
                    f"{config.frequency_hz / 1e6:.7g} MHz · {repetitions}.",
                    BLUE,
                )
        except Exception as exc:
            self._error("Envoi de la trame", exc)
        finally:
            self.serial_pending = False
            self._buttons()
            self._update()

    async def _stop(self, _: Any) -> None:
        if self.serial_pending or self.programming_pending:
            return
        self.serial_pending = True
        self._buttons()
        self._update()
        try:
            async with self.serial_lock:
                if self.device is None or not self.device.connected:
                    raise ValueError("Aucun appareil connecté.")
                try:
                    status = await asyncio.to_thread(self.device.stop)
                except CommandTimeout as exc:
                    await self._recover_command_timeout(exc)
                    raise
                self.command_uncertain = False
                self._status_received(status)
                self._log("STOP · sorties ramenées au repos.", AMBER)
        except Exception as exc:
            self._error("Arrêt", exc)
        finally:
            self.serial_pending = False
            self._buttons()
            self._update()

    async def _poll(self) -> None:
        while not self.closing:
            await asyncio.sleep(
                0.2 if self.device_status is not None and self.device_status.busy else 1.0
            )
            if (
                self.serial_pending
                or self.programming_pending
                or self.device is None
                or not self.device.connected
            ):
                continue
            try:
                async with self.serial_lock:
                    if self.device is None or not self.device.connected:
                        continue
                    old_busy = bool(self.device_status is not None and self.device_status.busy)
                    status = await asyncio.to_thread(self.device.status)
                    self._status_received(status)
                    if old_busy and not status.busy:
                        self._log(f"Émission terminée · {status.completed} trame(s).", GREEN)
                    self._update()
            except asyncio.CancelledError:
                raise
            except Exception as exc:
                self._log(f"Connexion interrompue : {exc}", RED)
                async with self.serial_lock:
                    if self.device is not None:
                        await asyncio.to_thread(self.device.close)
                    self.device = None
                    self.device_status = None
                    self.last_sent = None
                    self._firmware_identified(None)
                self.connection_status.value = "Connexion interrompue · reconnectez la carte"
                self.connection_status.color = RED
                self.hardware_status.value = "État de la carte inconnu"
                self._buttons()
                self._update()

    def _simulate_clicked(self, _: Any) -> None:
        self._changed()
        if self.waveform is not None:
            self.tabs.selected_index = 1
            self._log("Chronogramme idéal actualisé depuis les paramètres.")
            self._update()

    def _set_profile(self, config: FrameConfig) -> None:
        connected = self.device is not None and self.device.connected
        achievable = {setting.core_hz for setting in pll_settings()}
        if not connected and config.core_hz != self.core_hz and config.core_hz in achievable:
            # Sans carte, l'interface adopte l'horloge prévue par le profil.
            self.core_hz = config.core_hz
            self.core_clock.value = str(config.core_hz)
        self.base.value = "hex"
        self.previous_base = "hex"
        self.word.value = f"{config.word:X}"
        self.bit_count.value = str(config.bit_count)
        self.frequency.value = f"{config.frequency_hz / 1e6:.9g}"
        # En CLK libre, le champ LATCH porte l'impulsion visible (k périodes).
        self.latch_ns.value = f"{config.latch_active_ticks * config.tick_ns:.9g}"
        self.gap_ns.value = f"{config.gap_ticks * config.tick_ns:.9g}"
        self.free_clock.value = config.free_clock
        if config.core_hz == self.core_hz:
            self.divider.value = str(config.divider)
        else:
            # Profil prévu pour une autre horloge : fréquence et durées en ns
            # sont conservées puis requantifiées pour le firmware courant.
            self._log(
                f"Profil prévu pour un cœur à {config.core_hz / 1e6:g} MHz, converti pour "
                f"{self.core_hz / 1e6:g} MHz ; vérifier la fréquence et les durées obtenues.",
                AMBER,
            )
            try:
                self.divider.value = str(divider_for_frequency(config.frequency_hz, self.core_hz))
            except ValueError:
                self.divider.value = "1"
        self.continuous.value = config.continuous
        self.repeat.disabled = config.continuous
        if not config.continuous:
            self.repeat.value = str(config.repeat_count)
        self.lsb.value = config.lsb_first
        self.latch_low.value = config.latch_active_low
        self._changed()

    @staticmethod
    def _path(value: str | None) -> Path:
        if not value or not value.strip():
            raise ValueError("Renseignez un chemin de fichier.")
        return Path(value.strip()).expanduser().resolve()

    async def _load_profile(self, _: Any) -> None:
        try:
            path = self._path(self.profile_path.value)
            config = await asyncio.to_thread(load_profile, path)
            self._set_profile(config)
            self.profile_message.value = f"Profil chargé : {path}"
            self.profile_message.color = GREEN
            self._log(self.profile_message.value)
        except Exception as exc:
            self.profile_message.value = str(exc)
            self.profile_message.color = RED
            self._error("Chargement du profil", exc)
        self._update()

    async def _save_profile(self, _: Any) -> None:
        try:
            config = self._config()
            path = self._path(self.profile_path.value)
            await asyncio.to_thread(path.parent.mkdir, parents=True, exist_ok=True)
            await asyncio.to_thread(save_profile, config, path)
            self.profile_message.value = f"Profil enregistré : {path}"
            self.profile_message.color = GREEN
            self._log(self.profile_message.value)
        except Exception as exc:
            self.profile_message.value = str(exc)
            self.profile_message.color = RED
            self._error("Enregistrement du profil", exc)
        self._update()

    async def _export(self, extension: str) -> None:
        try:
            waveform = simulate(self._config(), max_frames=4)
            path = self._path(self.export_path.value).with_suffix(extension)
            await asyncio.to_thread(path.parent.mkdir, parents=True, exist_ok=True)
            if extension == ".svg":
                await asyncio.to_thread(
                    path.write_text, waveform_svg(waveform, width=1600), encoding="utf-8"
                )
            elif extension == ".csv":
                await asyncio.to_thread(export_csv, waveform, path)
            else:
                await asyncio.to_thread(export_vcd, waveform, path)
            self.export_message.value = f"Export enregistré : {path}"
            if waveform.truncated:
                self.export_message.value += " · limité aux 4 premières trames"
            self.export_message.color = GREEN
            self._log(self.export_message.value)
        except Exception as exc:
            self.export_message.value = str(exc)
            self.export_message.color = RED
            self._error("Export du chronogramme", exc)
        self._update()

    async def _export_svg(self, _: Any) -> None:
        await self._export(".svg")

    async def _export_csv(self, _: Any) -> None:
        await self._export(".csv")

    async def _export_vcd(self, _: Any) -> None:
        await self._export(".vcd")

    def _toolchain(self) -> Toolchain:
        path = self._path(self.toolchain_path.value)
        return Toolchain(ToolchainConfig.from_json(path), self.project_root)

    def _worker_log(self, message: str) -> None:
        if self.loop is not None and not self.closing:
            self.loop.call_soon_threadsafe(self._queue_worker_log, str(message))

    def _queue_worker_log(self, message: str) -> None:
        if self.closing:
            return
        self.worker_messages.append(message)
        if self.log_flush_handle is None and self.loop is not None:
            # Synthesis can emit thousands of lines per second. Batch updates
            # rather than serializing the complete Flet control tree per line.
            self.log_flush_handle = self.loop.call_later(0.1, self._flush_worker_logs)

    def _flush_worker_logs(self) -> None:
        if self.log_flush_handle is not None:
            self.log_flush_handle.cancel()
            self.log_flush_handle = None
        if self.worker_messages:
            messages = "\n".join(self.worker_messages)
            self.worker_messages.clear()
            self._log(messages)

    async def _tool_action(
        self, title: str, action: Callable[[], Any], *, blocks_uart: bool = False
    ) -> Any:
        self.tool_pending = True
        self.programming_pending = blocks_uart
        self.tool_panel.visible = True
        self.tool_progress.visible = True
        self.tool_message.value = f"{title} en cours… Consultez le journal pour les détails."
        self.tool_message.color = AMBER
        self._buttons()
        self._update()
        try:
            result = await asyncio.to_thread(action)
            self._flush_worker_logs()
            self.tool_message.value = f"{title} : opération terminée."
            self.tool_message.color = GREEN
            self._log(self.tool_message.value, GREEN)
            return result
        except Exception as exc:
            self._flush_worker_logs()
            self.tool_message.value = f"{title} : {exc}"
            self.tool_message.color = RED
            self._error(title, exc)
            return None
        finally:
            self.tool_pending = False
            self.programming_pending = False
            self.tool_progress.visible = False
            self._buttons()
            self._update()

    async def _doctor(self, _: Any) -> None:
        if self.tool_pending:
            return

        def run() -> Any:
            return self._toolchain().doctor()

        results = await self._tool_action("Vérification des outils", run)
        if results is not None:
            self.doctor_results.controls = []
            for result in results:
                if isinstance(result, dict):
                    name = str(result.get("name", "Outil"))
                    ok = bool(result.get("ok", False))
                    detail = str(result.get("detail", result.get("message", "")))
                else:
                    name = str(getattr(result, "name", "Outil"))
                    ok = bool(getattr(result, "ok", False))
                    detail = str(getattr(result, "detail", getattr(result, "message", result)))
                self.doctor_results.controls.append(
                    ft.Row(
                        [
                            ft.Icon(
                                ft.Icons.CHECK_CIRCLE if ok else ft.Icons.ERROR_OUTLINE,
                                color=GREEN if ok else RED,
                                size=18,
                            ),
                            ft.Text(
                                f"{name} · {detail}",
                                size=12,
                                color=MUTED,
                                selectable=True,
                                expand=True,
                            ),
                        ]
                    )
                )
                self._log(f"{name} · {'OK' if ok else 'INDISPONIBLE'} · {detail}")
            self._update()

    async def _jtag_probe(self, _: Any) -> None:
        if self.tool_pending or self.serial_pending:
            return
        if isinstance(self.device, SerialDevice) and self.device.connected:
            await self._toggle_connection()
        dll = (self.ftdi_dll_path.value or "").strip()
        serial = (self.ftdi_serial.value or "").strip()
        self._log("JTAG : profil Digilent Arty · GPIO E8/EB et 00/60 · horloge 1 MHz.")
        result = await self._tool_action(
            "Détection JTAG Windows",
            lambda: probe_arty(serial=serial or None, dll_path=Path(dll) if dll else None),
        )
        if result is not None:
            self.tool_message.value = (
                f"Artix-7 100T détecté · IDCODE 0x{result.idcode:08X} · {result.serial}"
            )
            self._log(self.tool_message.value, GREEN)
            self._log("La détection JTAG ne confirme pas que le firmware UART est chargé.", BLUE)
            self._update()

    def _firmware_settings(self) -> FirmwareBuildConfig:
        try:
            core_hz = int(self.fw_core.value or "")
            drive = int(self.fw_drive.value or "")
        except ValueError as exc:
            raise ValueError("Choisir l'horloge du cœur et le courant de sortie.") from exc
        return FirmwareBuildConfig(
            core_hz=core_hz,
            data_pin=self.fw_pins["data_pin"].value or "",
            clock_pin=self.fw_pins["clock_pin"].value or "",
            latch_pin=self.fw_pins["latch_pin"].value or "",
            drive_ma=drive,
            slew=self.fw_slew.value or "",
        )

    def _refresh_firmware_summary(self) -> None:
        try:
            firmware = self._firmware_settings()
        except ValueError as exc:
            self.fw_summary.value = f"Configuration invalide : {exc}"
            self.fw_summary.color = RED
            self.fw_warnings.value = ""
            return
        self.fw_summary.value = (
            f"{'Firmware de référence' if firmware.is_reference else 'Firmware personnalisé'} · "
            f"{firmware.summary()} · CLK maximale {firmware.core_hz / 1e6:g} MHz"
        )
        self.fw_summary.color = BLUE
        self.fw_warnings.value = "\n".join(f"Attention : {note}" for note in firmware.warnings())

    def _firmware_changed(self, _: Any = None) -> None:
        self._refresh_firmware_summary()
        self._buttons()
        self._update()

    def _set_firmware(self, firmware: FirmwareBuildConfig) -> None:
        self.fw_core.value = str(firmware.core_hz)
        for field, control in self.fw_pins.items():
            control.value = getattr(firmware, field)
        self.fw_drive.value = str(firmware.drive_ma)
        self.fw_slew.value = firmware.slew
        self._firmware_changed()

    async def _load_firmware(self, _: Any) -> None:
        try:
            path = self._path(self.fw_config_path.value)
            firmware = await asyncio.to_thread(FirmwareBuildConfig.load, path)
            self._set_firmware(firmware)
            self._log(f"Configuration firmware chargée : {path}")
        except Exception as exc:
            self._error("Chargement de la configuration firmware", exc)

    async def _save_firmware(self, _: Any) -> None:
        try:
            firmware = self._firmware_settings()
            path = self._path(self.fw_config_path.value)
            await asyncio.to_thread(path.parent.mkdir, parents=True, exist_ok=True)
            await asyncio.to_thread(firmware.save, path)
            self._log(f"Configuration firmware enregistrée : {path}", GREEN)
        except Exception as exc:
            self._error("Enregistrement de la configuration firmware", exc)

    async def _build(self, _: Any) -> None:
        if self.tool_pending:
            return
        try:
            firmware = self._firmware_settings()
        except ValueError as exc:
            self._error("Compilation FPGA", exc)
            return
        self._log(f"Compilation locale : {firmware.summary()}.")
        result = await self._tool_action(
            "Compilation FPGA",
            lambda: self._toolchain().build(log=self._worker_log, firmware=firmware),
        )
        if result is not None:
            self._select_firmware(Path(result), firmware)
            self.tool_message.value = f"Bitstream créé : {result} · {firmware.summary()}"
            self._update()

    async def _remote_build(self, _: Any) -> None:
        if self.tool_pending:
            return
        try:
            firmware = self._firmware_settings()
            target = RemoteBuildTarget(
                (self.gh_repository.value or "").strip(), (self.gh_ref.value or "").strip()
            )
            client = GitHubBuildClient(target, self.gh_token.value or "")
        except ValueError as exc:
            self._error("Compilation GitHub", exc)
            return
        destination = self.project_root / "builds"
        result = await self._tool_action(
            "Compilation GitHub",
            lambda: client.build(firmware, destination, progress=self._worker_log),
        )
        if result is not None:
            self._select_firmware(Path(result.bitstream), firmware)
            self.tool_message.value = f"Firmware téléchargé et vérifié : {result.bitstream}"
            self._log(self.tool_message.value, GREEN)
            self._log(
                "Charger ce .bit sous Windows, puis connecter la carte et lancer le test LED. "
                f"Exécution GitHub : {result.run_url}",
                BLUE,
            )
            self._update()

    async def _jtag_program(self, _: Any) -> None:
        if self.tool_pending or self.serial_pending:
            return
        try:
            bitstream = self._path(self.windows_bitstream_path.value)
            if not bitstream.is_file():
                raise ValueError("Indiquez un fichier .bit existant pour l'Arty A7-100T.")
        except (OSError, ValueError) as exc:
            self._error("Chargement Windows", exc)
            return
        if isinstance(self.device, SerialDevice) and self.device.connected:
            await self._toggle_connection()
        dll = (self.ftdi_dll_path.value or "").strip()
        serial = (self.ftdi_serial.value or "").strip()

        def run() -> Any:
            image = read_bitstream(bitstream)
            manifest = validate_programming_image(image, self.project_root)
            if manifest is not None:
                self._worker_log(
                    f"Firmware vérifié · sources {manifest['source_commit'][:7]} · "
                    f"Fmax {manifest['routed_core_fmax_mhz']:.2f} MHz."
                )
            self._worker_log(f"Bitstream {image.part} · SHA256 {image.sha256}")
            result = program_arty(
                image.payload, serial=serial or None, dll_path=Path(dll) if dll else None
            )
            return result, manifest

        outcome = await self._tool_action("Chargement SRAM Windows", run, blocks_uart=True)
        if outcome is not None:
            result, manifest = outcome
            if manifest is not None and "firmware_config" in manifest:
                self._select_firmware(
                    bitstream, FirmwareBuildConfig.from_dict(manifest["firmware_config"])
                )
            self.tool_message.value = f"SRAM chargée · {result.serial} · STAT 0x{result.status:08X}"
            self._log(self.tool_message.value, GREEN)
            self._log(
                "La configuration FPGA a abouti. Connectez le port UART pour vérifier PING ; "
                "ce contrôle ne valide ni le timing GPIO, ni le protocole du fichier chargé.",
                BLUE,
            )
            self._update()

    async def _program(self, _: Any) -> None:
        if self.tool_pending or self.serial_pending:
            return
        try:
            bitstream = self._path(self.bitstream_path.value)
            if not bitstream.is_file():
                raise ValueError(
                    "Bitstream introuvable. Compilez ce projet pour produire "
                    "un bitstream validé, puis utilisez le fichier créé."
                )
        except Exception as exc:
            self._error("Programmation FPGA", exc)
            return
        # Reconfiguration resets the UART receiver. Closing the old session
        # avoids interpreting a stale response as the next command's reply.
        if isinstance(self.device, SerialDevice) and self.device.connected:
            await self._toggle_connection()

        def program() -> bool:
            self._toolchain().program(bitstream, log=self._worker_log)
            return True

        result = await self._tool_action("Programmation SRAM", program, blocks_uart=True)
        if result is not None:
            self._log(
                "Le FPGA est configuré. Connectez le port UART dans Pilotage "
                "pour envoyer des trames.",
                BLUE,
            )

    async def _export_journal(self, _: Any) -> None:
        try:
            path = self._path(self.journal_path.value)
            await asyncio.to_thread(path.parent.mkdir, parents=True, exist_ok=True)
            await asyncio.to_thread(
                path.write_text, "\n".join(self.log_lines) + "\n", encoding="utf-8"
            )
            self._log(f"Journal enregistré : {path}", GREEN)
        except Exception as exc:
            self._error("Export du journal", exc)

    def _clear_journal(self, _: Any) -> None:
        self.log_lines.clear()
        self.journal.controls.clear()
        self._update()

    async def shutdown(self, _: Any = None) -> None:
        self.closing = True
        if self.log_flush_handle is not None:
            self.log_flush_handle.cancel()
            self.log_flush_handle = None
        if self.poll_task is not None:
            self.poll_task.cancel()
            try:
                await self.poll_task
            except asyncio.CancelledError:
                pass
        async with self.serial_lock:
            if self.device is not None:
                await asyncio.to_thread(self.device.close)
            self.device = None

    async def start(self) -> None:
        self.loop = asyncio.get_running_loop()
        self.page.on_disconnect = self.shutdown
        self.page.add(self.layout())
        self._changed()
        self._log("Arty Frame Studio · mode démo disponible sans carte et sans outils FPGA.", BLUE)
        await self._refresh_ports()
        await self._toggle_connection()
        self.poll_task = asyncio.create_task(self._poll())


async def main(page: ft.Page) -> None:
    page.title = "Arty Frame Studio · A7-100T"
    page.theme_mode = ft.ThemeMode.DARK
    page.theme = ft.Theme(color_scheme_seed=AMBER, font_family="Roboto")
    page.bgcolor = BG
    page.padding = 24
    page.window.width = 1220
    page.window.height = 930
    page.window.min_width = 760
    page.window.min_height = 680
    await Studio(page).start()


def run() -> None:
    """Console entry point for the desktop application."""
    ft.app(target=main)


if __name__ == "__main__":
    run()
