"""French Flet desktop interface for Arty Frame Studio.

The host schedules commands over USB/UART. All waveform edges are generated by
the FPGA; the host application never attempts to bit-bang GPIO pins.
"""

from __future__ import annotations

import asyncio
import math
import os
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Any

import flet as ft  # type: ignore[import-untyped]
import flet.canvas as cv  # type: ignore[import-untyped]

from .model import (
    FrameConfig,
    divider_for_frequency,
    load_profile,
    parse_word,
    save_profile,
)
from .protocol import DeviceStatus
from .simulation import Waveform, export_csv, export_vcd, simulate, waveform_svg
from .toolchain import Toolchain, ToolchainConfig
from .transport import DemoDevice, SerialDevice, list_ports

BG = "#0C1423"
PANEL = "#142136"
LINE = "#273A54"
TEXT = "#E7EDF5"
MUTED = "#A5B4C9"
AMBER = "#F4B759"
BLUE = "#75B9F4"
GREEN = "#79CFB0"
RED = "#FF8E91"
CHART_HEIGHT = 332
SIGNALS = (("DATA", "data", "#2563EB"), ("CLK", "clk", "#B45309"), ("LATCH", "latch", "#9333EA"))


def ticks_from_ns(value: str) -> int:
    """Round a finite nonnegative duration to the hardware's 2.5 ns grid."""
    ns = float(value.strip().replace(",", "."))
    if not math.isfinite(ns) or ns < 0:
        raise ValueError("La durée doit être un nombre positif ou nul.")
    return int(math.floor(ns / 2.5 + 0.5))


def format_duration(ns: float) -> str:
    if ns >= 1e9:
        return f"{ns / 1e9:.4g} s"
    if ns >= 1e6:
        return f"{ns / 1e6:.4g} ms"
    if ns >= 1e3:
        return f"{ns / 1e3:.4g} µs"
    return f"{ns:.4g} ns"


def waveform_signal_points(
    waveform: Waveform, signal: str, width: float
) -> list[tuple[float, float]]:
    """Exact digital steps for one trace, scaled to the available canvas width."""
    if signal not in ("data", "clk", "latch"):
        raise ValueError("Signal inconnu.")
    if not math.isfinite(width) or width < 200:
        raise ValueError("Largeur du chronogramme insuffisante.")
    row = ("data", "clk", "latch").index(signal)
    high, low = 84.0 + row * 64, 114.0 + row * 64
    left, right = 92.0, width - 28

    def position(ticks: int) -> float:
        return left + ticks / waveform.duration_ticks * (right - left)

    first = waveform.transitions[0]
    previous = high if getattr(first, signal) else low
    points = [(position(first.time_ticks), previous)]
    for transition in waveform.transitions[1:]:
        x = position(transition.time_ticks)
        level = high if getattr(transition, signal) else low
        points.append((x, previous))
        if level != previous:
            points.append((x, level))
        previous = level
    if points[-1][0] < right:
        points.append((right, previous))
    return points


def waveform_canvas_shapes(waveform: Waveform, width: float = 1200) -> list[Any]:
    """Render traces and text natively; SVG remains an independent export format."""
    left, right = 92.0, width - 28
    shapes: list[Any] = [
        cv.Rect(0, 0, width, CHART_HEIGHT, border_radius=12, paint=ft.Paint(color="#F8FAFC")),
        cv.Text(
            22,
            14,
            "Chronogramme numérique idéal",
            style=ft.TextStyle(size=16, color="#0F172A", weight=ft.FontWeight.W_700),
        ),
        cv.Text(
            22,
            40,
            f"{waveform.config.bit_count} bits · "
            f"{waveform.config.frequency_hz / 1e6:.6g} MHz · "
            f"{'LSB' if waveform.config.lsb_first else 'MSB'} en premier",
            style=ft.TextStyle(size=12, color="#475569"),
        ),
    ]
    grid_paint = ft.Paint(
        color="#E2E8F0", stroke_width=1, style=ft.PaintingStyle.STROKE, stroke_dash_pattern=[3, 4]
    )
    unit, scale = ("µs", 1000) if waveform.duration_ns >= 1000 else ("ns", 1)
    for index in range(11):
        x = left + index / 10 * (right - left)
        shapes.extend(
            [
                cv.Line(x, 70, x, 260, paint=grid_paint),
                cv.Text(
                    x,
                    270,
                    f"{waveform.duration_ns * index / 10 / scale:.3g}",
                    alignment=ft.alignment.top_center,
                    style=ft.TextStyle(size=10, color="#475569"),
                ),
            ]
        )
    for row, (label, signal, color) in enumerate(SIGNALS):
        points = waveform_signal_points(waveform, signal, width)
        shapes.append(
            cv.Text(
                20,
                91 + row * 64,
                label,
                style=ft.TextStyle(size=13, color=color, weight=ft.FontWeight.W_700),
            )
        )
        elements = [cv.Path.MoveTo(*points[0])]
        elements.extend(cv.Path.LineTo(*point) for point in points[1:])
        shapes.append(
            cv.Path(
                elements=elements,
                paint=ft.Paint(color=color, stroke_width=2, style=ft.PaintingStyle.STROKE),
                data=f"signal:{signal}",
            )
        )
    bit_width = 2 * waveform.config.divider / waveform.duration_ticks * (right - left)
    if bit_width >= 14:
        for index, bit in enumerate(waveform.config.bits):
            sample_tick = (2 * index + 1) * waveform.config.divider
            x = left + sample_tick / waveform.duration_ticks * (right - left)
            shapes.append(
                cv.Text(
                    x,
                    126,
                    str(bit),
                    alignment=ft.alignment.center,
                    style=ft.TextStyle(size=10, color="#2563EB"),
                )
            )
    shapes.append(
        cv.Text(
            22,
            305,
            f"Temps ({unit}) · Échantillonnage DATA au front montant de CLK",
            style=ft.TextStyle(size=11, color="#475569"),
        )
    )
    return shapes


def project_directory() -> Path:
    configured = os.environ.get("ARTY_FRAME_PROJECT")
    if configured:
        return Path(configured).expanduser().resolve()
    if (Path.cwd() / "firmware").is_dir():
        return Path.cwd()
    return Path(__file__).resolve().parents[2]


class Studio:
    """Own controls, connection lifecycle and asynchronous background work."""

    def __init__(self, page: ft.Page, project_root: Path | None = None) -> None:
        self.page = page
        self.project_root = project_root or project_directory()
        self.device: SerialDevice | DemoDevice | None = None
        self.device_status: DeviceStatus | None = None
        self.serial_lock = asyncio.Lock()
        self.serial_pending = False
        self.tool_pending = False
        self.closing = False
        self.poll_task: asyncio.Task[Any] | None = None
        self.current_config: FrameConfig | None = None
        self.waveform: Waveform | None = None
        self.last_sent: FrameConfig | None = None
        self.previous_base = "hex"
        self.loop: asyncio.AbstractEventLoop | None = None
        self.worker_messages: list[str] = []
        self.log_flush_handle: asyncio.TimerHandle | None = None
        self.chart_width = 1200.0
        self._create_controls()

    def _field(
        self,
        label: str,
        value: str,
        *,
        width: int = 180,
        on_change: Callable[..., Any] | None = None,
        helper: str | None = None,
    ) -> ft.TextField:
        return ft.TextField(
            label=label,
            value=value,
            width=width,
            dense=True,
            border_color=LINE,
            focused_border_color=AMBER,
            text_style=ft.TextStyle(color=TEXT),
            helper_text=helper,
            on_change=on_change or self._changed,
        )

    def _card(self, *controls: ft.Control) -> ft.Container:
        return ft.Container(
            content=ft.Column(list(controls), spacing=15),
            bgcolor=PANEL,
            border=ft.border.all(1, LINE),
            border_radius=16,
            padding=20,
        )

    @staticmethod
    def _heading(title: str, subtitle: str | None = None) -> ft.Control:
        controls: list[ft.Control] = [ft.Text(title, size=18, weight=ft.FontWeight.W_600)]
        if subtitle:
            controls.append(ft.Text(subtitle, size=12, color=MUTED))
        return ft.Column(controls, spacing=4)

    def _create_controls(self) -> None:
        self.mode = ft.Dropdown(
            label="Connexion",
            value="demo",
            width=210,
            options=[
                ft.dropdown.Option("demo", "Démo locale"),
                ft.dropdown.Option("uart", "Carte · USB / UART"),
            ],
            on_change=self._mode_changed,
        )
        self.port = ft.Dropdown(label="Port série", width=280, disabled=True, options=[])
        self.refresh_button = ft.IconButton(
            icon=ft.Icons.REFRESH,
            tooltip="Actualiser les ports série",
            on_click=self._refresh_ports,
        )
        self.connect_button = ft.ElevatedButton(
            "Connecter",
            icon=ft.Icons.USB,
            on_click=self._toggle_connection,
        )
        self.connection_status = ft.Text("Déconnecté", color=MUTED)
        self.hardware_status = ft.Text("Aucune émission", size=12, color=MUTED)
        self.word = self._field("Valeur de la trame", "2AAAAAA", width=340)
        self.word.text_style = ft.TextStyle(font_family="monospace", color=TEXT)
        self.base = ft.Dropdown(
            label="Notation",
            value="hex",
            width=180,
            options=[
                ft.dropdown.Option("bin", "Binaire"),
                ft.dropdown.Option("hex", "Hexadécimal"),
                ft.dropdown.Option("dec", "Décimal"),
            ],
            on_change=self._base_changed,
        )
        self.bit_count = self._field("Nombre de bits", "26", width=145, helper="1 à 26 bits")
        self.frequency = self._field(
            "Fréquence demandée (MHz)",
            "10",
            width=215,
            on_change=self._frequency_changed,
            helper="200 / N MHz",
        )
        self.divider = self._field(
            "Diviseur N",
            "20",
            width=145,
            on_change=self._divider_changed,
            helper="Entier de 1 à 65 535",
        )
        self.latch_ns = self._field("Impulsion LATCH (ns)", "20", width=205)
        self.gap_ns = self._field("Pause après LATCH (ns)", "100", width=205)
        self.repeat = self._field(
            "Répétitions", "1", width=145, helper="1 à 65 535 · émission finie"
        )
        self.lsb = ft.Switch(label="LSB en premier", value=False, on_change=self._changed)
        self.latch_low = ft.Switch(label="LATCH actif bas", value=False, on_change=self._changed)
        self.frequency_actual = ft.Text(size=19, color=AMBER, weight=ft.FontWeight.W_600)
        self.timing_summary = ft.Text(color=MUTED, size=12)
        self.binary_preview = ft.Text(size=19, color=BLUE, selectable=True, font_family="monospace")
        self.order_preview = ft.Text(size=12, color=MUTED, selectable=True)
        self.validation = ft.Text(size=12, color=RED)
        self.send_button = ft.ElevatedButton(
            "Envoyer la trame",
            icon=ft.Icons.PLAY_ARROW,
            on_click=self._send,
            disabled=True,
            style=ft.ButtonStyle(bgcolor=AMBER, color=BG),
        )
        self.stop_button = ft.OutlinedButton(
            "Arrêter",
            icon=ft.Icons.STOP,
            on_click=self._stop,
            disabled=True,
        )
        self.simulate_button = ft.OutlinedButton(
            "Actualiser le chronogramme",
            icon=ft.Icons.SHOW_CHART,
            on_click=self._simulate_clicked,
        )
        self.profile_path = self._field(
            "Fichier de profil JSON",
            str(self.project_root / "profiles" / "default.json"),
            width=600,
            on_change=lambda _: None,
        )
        self.profile_message = ft.Text(size=12, color=MUTED)
        self.wave_canvas = cv.Canvas(
            shapes=[],
            width=1200,
            height=CHART_HEIGHT,
            on_resize=self._chart_resized,
            resize_interval=100,
            visible=False,
        )
        self.wave_note = ft.Text(size=12, color=MUTED)
        self.export_path = self._field(
            "Chemin des exports (extension remplacée selon le format)",
            str(self.project_root / "exports" / "chronogramme"),
            width=650,
            on_change=lambda _: None,
        )
        self.export_message = ft.Text(size=12, color=MUTED, selectable=True)
        self.toolchain_path = self._field(
            "Configuration de la chaîne open source (JSON)",
            str(self.project_root / "toolchain.json"),
            width=650,
            on_change=lambda _: None,
        )
        self.bitstream_path = self._field(
            "Bitstream validé de ce projet (.bit)",
            str(self.project_root / "build" / "arty_frame.bit"),
            width=650,
            on_change=lambda _: None,
        )
        self.doctor_button = ft.OutlinedButton(
            "Vérifier les outils",
            icon=ft.Icons.FACT_CHECK,
            on_click=self._doctor,
        )
        self.build_button = ft.ElevatedButton(
            "Compiler le FPGA",
            icon=ft.Icons.BUILD,
            on_click=self._build,
        )
        self.program_button = ft.ElevatedButton(
            "Programmer la SRAM",
            icon=ft.Icons.MEMORY,
            on_click=self._program,
            style=ft.ButtonStyle(bgcolor=AMBER, color=BG),
        )
        self.tool_progress = ft.ProgressBar(visible=False, color=AMBER)
        self.tool_message = ft.Text(size=12, color=MUTED, selectable=True)
        self.doctor_results = ft.Column(spacing=5)
        self.journal = ft.ListView(expand=True, spacing=3, auto_scroll=True)
        self.journal_path = self._field(
            "Fichier du journal",
            str(self.project_root / "exports" / "journal.txt"),
            width=650,
            on_change=lambda _: None,
        )
        self.log_lines: list[str] = []

    def layout(self) -> ft.Control:
        connection = self._card(
            self._heading(
                "Connexion au moteur",
                "USB / UART 115 200 bauds · les fronts sont produits dans le FPGA",
            ),
            ft.Row([self.mode, self.port, self.refresh_button, self.connect_button], wrap=True),
            ft.Row([self.connection_status, self.hardware_status], wrap=True, spacing=24),
        )
        frame = self._card(
            self._heading(
                "Trame série",
                "DATA transmet un bit par cycle ; CLK et LATCH utilisent deux autres broches",
            ),
            ft.Row([self.word, self.base, self.bit_count], wrap=True),
            self.binary_preview,
            self.order_preview,
            ft.Row([self.lsb, self.latch_low], wrap=True),
        )
        timing = self._card(
            self._heading(
                "Horloge et séquencement",
                "CLK en rafales · repos bas · échantillonnage au front montant",
            ),
            ft.Row([self.frequency, self.divider, self.repeat], wrap=True),
            self.frequency_actual,
            ft.Row([self.latch_ns, self.gap_ns], wrap=True),
            self.timing_summary,
            ft.Text(
                "Les durées sont arrondies sur des pas de 2,5 ns. À 200 MHz, "
                "la validation temporelle et une liaison électrique adaptée sont nécessaires.",
                size=12,
                color=MUTED,
            ),
            self.validation,
            ft.Row([self.send_button, self.stop_button, self.simulate_button], wrap=True),
        )
        profiles = self._card(
            self._heading("Profils", "Les fichiers conservent tous les paramètres de la trame"),
            ft.Row([self.profile_path], wrap=True),
            ft.Row(
                [
                    ft.OutlinedButton(
                        "Charger", icon=ft.Icons.FOLDER_OPEN, on_click=self._load_profile
                    ),
                    ft.OutlinedButton(
                        "Enregistrer", icon=ft.Icons.SAVE, on_click=self._save_profile
                    ),
                ],
                wrap=True,
            ),
            self.profile_message,
        )
        control_tab = ft.Column(
            [connection, frame, timing, profiles],
            spacing=14,
            scroll=ft.ScrollMode.AUTO,
            expand=True,
        )
        waveform_tab = ft.Column(
            [
                self._card(
                    self._heading(
                        "Chronogramme idéal",
                        "Aperçu calculé à partir des paramètres du panneau Pilotage",
                    ),
                    ft.Text(
                        "Le graphe représente les fronts attendus. Il ne mesure pas les broches "
                        "et ne simule pas l'intégrité du signal.",
                        size=12,
                        color=MUTED,
                    ),
                    self.wave_canvas,
                    self.wave_note,
                ),
                self._card(
                    self._heading(
                        "Exporter le chronogramme",
                        "SVG pour le partage · CSV des transitions · VCD pour GTKWave",
                    ),
                    ft.Row([self.export_path], wrap=True),
                    ft.Row(
                        [
                            ft.OutlinedButton("SVG", on_click=self._export_svg),
                            ft.OutlinedButton("CSV", on_click=self._export_csv),
                            ft.OutlinedButton("VCD", on_click=self._export_vcd),
                        ],
                        wrap=True,
                    ),
                    self.export_message,
                ),
            ],
            scroll=ft.ScrollMode.AUTO,
            spacing=14,
            expand=True,
        )
        fpga_tab = ft.Column(
            [
                self._card(
                    self._heading(
                        "Arty A7-100T",
                        "xc7a100tcsg324-1 · référence carte 100 MHz · génération interne 200 MHz",
                    ),
                    ft.Text(
                        "Chaîne : Yosys → nextpnr-xilinx → Project X-Ray → openFPGALoader.",
                        color=BLUE,
                    ),
                    ft.Text(
                        "Configurez les chemins des outils et de la base X-Ray "
                        "dans le fichier JSON. La compilation prépare le moteur série ; "
                        "les trames suivantes passent par UART.",
                        color=MUTED,
                        size=12,
                    ),
                    ft.Text(
                        "Brochage de départ : Pmod JB. Consultez le fichier de contraintes "
                        "et le guide "
                        "de câblage fourni avant de connecter votre périphérique (logique 3,3 V).",
                        color=MUTED,
                        size=12,
                    ),
                    ft.Text(
                        "JB1 / E15 : DATA · JB2 / E16 : CLK · JB3 / D15 : LATCH · "
                        "masse : JB5 ou JB11",
                        color=BLUE,
                        size=12,
                        selectable=True,
                    ),
                    ft.Row([self.toolchain_path], wrap=True),
                    ft.Row([self.doctor_button, self.build_button], wrap=True),
                    self.doctor_results,
                ),
                self._card(
                    self._heading(
                        "Programmer le bitstream",
                        "Chargement volatile en SRAM · la configuration est perdue à l'extinction",
                    ),
                    ft.Row([self.bitstream_path], wrap=True),
                    ft.Row([self.program_button], wrap=True),
                    self.tool_progress,
                    self.tool_message,
                    ft.Text(
                        "Les sorties rapides nécessitent un rapport de timing valide. "
                        "Le mode démo reste disponible sans outils FPGA installés.",
                        color=MUTED,
                        size=12,
                    ),
                ),
            ],
            scroll=ft.ScrollMode.AUTO,
            spacing=14,
            expand=True,
        )
        journal_tab = ft.Column(
            [
                self._heading(
                    "Journal de session",
                    "Commandes, réponses de la carte et messages de compilation",
                ),
                ft.Container(
                    self.journal,
                    expand=True,
                    bgcolor="#080E19",
                    padding=12,
                    border_radius=12,
                    border=ft.border.all(1, LINE),
                ),
                ft.Row([self.journal_path], wrap=True),
                ft.Row(
                    [
                        ft.OutlinedButton("Exporter le journal", on_click=self._export_journal),
                        ft.TextButton("Effacer", on_click=self._clear_journal),
                    ],
                    wrap=True,
                ),
            ],
            expand=True,
            spacing=12,
        )
        self.tabs = ft.Tabs(
            tabs=[
                ft.Tab(text="Pilotage", icon=ft.Icons.TUNE, content=control_tab),
                ft.Tab(text="Chronogramme", icon=ft.Icons.SHOW_CHART, content=waveform_tab),
                ft.Tab(text="FPGA", icon=ft.Icons.MEMORY, content=fpga_tab),
                ft.Tab(text="Journal", icon=ft.Icons.TERMINAL, content=journal_tab),
            ],
            selected_index=0,
            expand=True,
            animation_duration=180,
        )
        return ft.Column(
            [
                ft.Row(
                    [
                        ft.Container(
                            ft.Icon(ft.Icons.MEMORY, size=30, color=AMBER),
                            bgcolor=PANEL,
                            padding=12,
                            border_radius=14,
                        ),
                        ft.Column(
                            [
                                ft.Text("ARTY FRAME STUDIO", size=23, weight=ft.FontWeight.W_700),
                                ft.Text(
                                    "Série 26 bits · Horloge ajustable · Latch · Simulation",
                                    size=12,
                                    color=MUTED,
                                ),
                            ],
                            spacing=3,
                        ),
                    ],
                    spacing=14,
                ),
                self.tabs,
            ],
            spacing=18,
            expand=True,
        )

    def _config(self) -> FrameConfig:
        bits = int(self.bit_count.value or "")
        # The divider is authoritative, while the requested frequency must also
        # remain valid after edits to another field.
        requested_hz = float((self.frequency.value or "").replace(",", ".")) * 1e6
        divider_for_frequency(requested_hz)
        return FrameConfig(
            word=parse_word(self.word.value or "", self.base.value or "hex", bits),
            bit_count=bits,
            divider=int(self.divider.value or ""),
            latch_ticks=ticks_from_ns(self.latch_ns.value or ""),
            gap_ticks=ticks_from_ns(self.gap_ns.value or ""),
            repeat_count=int(self.repeat.value or ""),
            lsb_first=bool(self.lsb.value),
            latch_active_low=bool(self.latch_low.value),
        )

    def _update(self) -> None:
        if not self.closing:
            self.page.update()

    def _chart_resized(self, event: Any) -> None:
        width = float(event.width)
        if not math.isfinite(width) or width < 200 or abs(width - self.chart_width) < 0.5:
            return
        self.chart_width = width
        if self.waveform is not None:
            self.wave_canvas.shapes = waveform_canvas_shapes(self.waveform, width)
            self._update()

    def _changed(self, _: Any = None) -> None:
        try:
            config = self._config()
            waveform = simulate(config, max_frames=4)
            self.current_config = config
            self.waveform = waveform
            self.wave_canvas.shapes = waveform_canvas_shapes(waveform, self.chart_width)
            self.wave_canvas.visible = True
            self.frequency_actual.value = (
                f"Fréquence réalisée : {config.frequency_hz / 1e6:.7g} MHz · "
                f"200 MHz / {config.divider}"
            )
            self.binary_preview.value = f"{config.word:0{config.bit_count}b}"
            emitted = (
                self.binary_preview.value[::-1] if config.lsb_first else self.binary_preview.value
            )
            self.order_preview.value = (
                f"Ordre sur DATA → {emitted} · {'LSB' if config.lsb_first else 'MSB'} en premier"
            )
            self.timing_summary.value = (
                f"LATCH {config.latch_ticks * 2.5:g} ns · Pause {config.gap_ticks * 2.5:g} ns · "
                f"Période de trame {format_duration(config.frame_duration_ns)} · "
                f"Durée totale {format_duration(config.total_duration_ns)}"
            )
            self.wave_note.value = (
                f"{waveform.frames_simulated} trame(s) affichée(s) sur {config.repeat_count} · "
                f"fenêtre {format_duration(waveform.duration_ns)} · résolution 2,5 ns"
                + (" · aperçu limité aux 4 premières trames" if waveform.truncated else "")
            )
            self.validation.value = ""
        except (ValueError, TypeError, OverflowError) as exc:
            self.current_config = None
            self.waveform = None
            self.wave_canvas.shapes = []
            self.wave_canvas.visible = False
            self.wave_note.value = "Complétez les paramètres pour afficher le chronogramme."
            self.validation.value = f"Paramètre invalide : {exc}"
            self.frequency_actual.value = "Paramètres à corriger"
            self.binary_preview.value = "—"
            self.order_preview.value = ""
            self.timing_summary.value = ""
        self._buttons()
        self._update()

    def _frequency_changed(self, _: Any) -> None:
        try:
            hz = float((self.frequency.value or "").replace(",", ".")) * 1e6
            self.divider.value = str(divider_for_frequency(hz))
        except (ValueError, OverflowError) as exc:
            self.current_config = None
            self.waveform = None
            self.wave_canvas.shapes = []
            self.wave_canvas.visible = False
            self.validation.value = f"Fréquence invalide : {exc}"
            self.frequency_actual.value = "Fréquence demandée à corriger"
            self._buttons()
            self._update()
            return
        self._changed()

    def _divider_changed(self, _: Any) -> None:
        try:
            divider = int(self.divider.value or "")
            if divider > 0:
                self.frequency.value = f"{200 / divider:.9g}"
        except ValueError:
            pass
        self._changed()

    def _base_changed(self, _: Any) -> None:
        try:
            word = parse_word(
                self.word.value or "", self.previous_base, int(self.bit_count.value or "")
            )
            base = self.base.value
            self.word.value = (
                f"{word:0{int(self.bit_count.value or '')}b}"
                if base == "bin"
                else f"{word:X}"
                if base == "hex"
                else str(word)
            )
        except (ValueError, TypeError):
            pass
        self.previous_base = self.base.value or "hex"
        self._changed()

    def _buttons(self) -> None:
        connected = bool(self.device is not None and self.device.connected)
        busy = bool(self.device_status is not None and self.device_status.busy)
        self.send_button.disabled = (
            not connected or self.current_config is None or busy or self.serial_pending
        )
        self.stop_button.disabled = not connected or self.serial_pending
        self.simulate_button.disabled = self.current_config is None
        self.connect_button.disabled = self.serial_pending
        self.connect_button.text = "Déconnecter" if connected else "Connecter"
        self.mode.disabled = connected or self.serial_pending
        self.port.disabled = connected or self.mode.value != "uart" or self.serial_pending
        self.refresh_button.disabled = self.serial_pending
        for control in (self.doctor_button, self.build_button, self.program_button):
            control.disabled = self.tool_pending
        self.program_button.disabled = self.tool_pending or self.serial_pending

    def _log(self, message: str, color: str = MUTED) -> None:
        for line in str(message).splitlines():
            stamp = datetime.now().strftime("%H:%M:%S")
            entry = f"{stamp}  {line}"
            self.log_lines.append(entry)
            self.journal.controls.append(
                ft.Text(entry, color=color, size=12, selectable=True, font_family="monospace")
            )
        self.log_lines = self.log_lines[-1000:]
        self.journal.controls = self.journal.controls[-1000:]
        self._update()

    def _error(self, action: str, exc: Exception) -> None:
        message = f"{action} : {exc}"
        self._log(message, RED)
        if not self.closing:
            self.page.open(ft.SnackBar(ft.Text(message), bgcolor="#73353F", duration=8000))

    async def _mode_changed(self, _: Any) -> None:
        self._buttons()
        self._update()

    async def _refresh_ports(self, _: Any = None) -> None:
        try:
            ports = await asyncio.to_thread(list_ports)
            current = self.port.value
            self.port.options = [
                ft.dropdown.Option(p.device, f"{p.device} · {p.description}") for p in ports
            ]
            available = {p.device for p in ports}
            self.port.value = (
                current if current in available else (ports[0].device if ports else None)
            )
            self._log(f"Ports série détectés : {len(ports)}.")
            self._update()
        except Exception as exc:
            self._error("Détection des ports", exc)

    async def _toggle_connection(self, _: Any = None) -> None:
        if self.serial_pending:
            return
        self.serial_pending = True
        self._buttons()
        self._update()
        try:
            async with self.serial_lock:
                if self.device is not None and self.device.connected:
                    await asyncio.to_thread(self.device.close)
                    self.device = None
                    self.device_status = None
                    self.last_sent = None
                    self.connection_status.value = "Déconnecté"
                    self.connection_status.color = MUTED
                    self.hardware_status.value = "Aucune émission"
                    self._log("Connexion fermée.")
                else:
                    device: SerialDevice | DemoDevice
                    if self.mode.value == "uart":
                        if not self.port.value:
                            raise ValueError(
                                "Sélectionnez un port série ou branchez la carte puis actualisez."
                            )
                        device = SerialDevice(self.port.value, baudrate=115200)
                    else:
                        device = DemoDevice()
                    try:
                        status = await asyncio.to_thread(device.connect)
                    except Exception:
                        await asyncio.to_thread(device.close)
                        raise
                    self.device = device
                    self.last_sent = None
                    self._status_received(status)
                    label = (
                        "Démo locale · aucun signal physique"
                        if self.mode.value == "demo"
                        else f"Arty · {self.port.value}"
                    )
                    self.connection_status.value = label
                    self.connection_status.color = GREEN
                    self._log(f"Connecté : {label}.", GREEN)
        except Exception as exc:
            self._error("Connexion", exc)
        finally:
            self.serial_pending = False
            self._buttons()
            self._update()

    def _status_received(self, status: DeviceStatus) -> None:
        self.device_status = status
        state = "Émission en cours" if status.busy else "Prêt"
        total = f" / {self.last_sent.repeat_count}" if self.last_sent is not None else ""
        self.hardware_status.value = f"{state} · {status.completed}{total} trame(s) terminée(s)"
        self.hardware_status.color = AMBER if status.busy else MUTED
        self._buttons()

    async def _send(self, _: Any) -> None:
        if self.serial_pending:
            return
        try:
            config = self._config()
        except (ValueError, TypeError, OverflowError) as exc:
            self._error("Envoi impossible", exc)
            return
        self.serial_pending = True
        self._buttons()
        self._update()
        try:
            async with self.serial_lock:
                if self.device is None or not self.device.connected:
                    raise ValueError("Connectez la carte ou le mode démo avant l'envoi.")
                status = await asyncio.to_thread(self.device.send, config)
                self.last_sent = config
                self._status_received(status)
                self._log(
                    f"SEND · {config.bit_count} bits · 0x{config.word:X} · "
                    f"{config.frequency_hz / 1e6:.7g} MHz · {config.repeat_count} répétition(s).",
                    BLUE,
                )
        except Exception as exc:
            self._error("Envoi de la trame", exc)
        finally:
            self.serial_pending = False
            self._buttons()
            self._update()

    async def _stop(self, _: Any) -> None:
        if self.serial_pending:
            return
        self.serial_pending = True
        self._buttons()
        self._update()
        try:
            async with self.serial_lock:
                if self.device is None or not self.device.connected:
                    raise ValueError("Aucun appareil connecté.")
                self._status_received(await asyncio.to_thread(self.device.stop))
                self._log("STOP · sorties ramenées au repos.", AMBER)
        except Exception as exc:
            self._error("Arrêt", exc)
        finally:
            self.serial_pending = False
            self._buttons()
            self._update()

    async def _poll(self) -> None:
        while not self.closing:
            await asyncio.sleep(
                0.2 if self.device_status is not None and self.device_status.busy else 1.0
            )
            if self.serial_pending or self.device is None or not self.device.connected:
                continue
            try:
                async with self.serial_lock:
                    if self.device is None or not self.device.connected:
                        continue
                    old_busy = bool(self.device_status is not None and self.device_status.busy)
                    status = await asyncio.to_thread(self.device.status)
                    self._status_received(status)
                    if old_busy and not status.busy:
                        self._log(f"Émission terminée · {status.completed} trame(s).", GREEN)
                    self._update()
            except asyncio.CancelledError:
                raise
            except Exception as exc:
                self._log(f"Connexion interrompue : {exc}", RED)
                async with self.serial_lock:
                    if self.device is not None:
                        await asyncio.to_thread(self.device.close)
                    self.device = None
                    self.device_status = None
                self.connection_status.value = "Connexion interrompue · reconnectez la carte"
                self.connection_status.color = RED
                self._buttons()
                self._update()

    def _simulate_clicked(self, _: Any) -> None:
        self._changed()
        if self.waveform is not None:
            self.tabs.selected_index = 1
            self._log("Chronogramme idéal actualisé depuis les paramètres.")
            self._update()

    def _set_profile(self, config: FrameConfig) -> None:
        self.base.value = "hex"
        self.previous_base = "hex"
        self.word.value = f"{config.word:X}"
        self.bit_count.value = str(config.bit_count)
        self.divider.value = str(config.divider)
        self.frequency.value = f"{config.frequency_hz / 1e6:.9g}"
        self.latch_ns.value = f"{config.latch_ticks * 2.5:g}"
        self.gap_ns.value = f"{config.gap_ticks * 2.5:g}"
        self.repeat.value = str(config.repeat_count)
        self.lsb.value = config.lsb_first
        self.latch_low.value = config.latch_active_low
        self._changed()

    @staticmethod
    def _path(value: str | None) -> Path:
        if not value or not value.strip():
            raise ValueError("Renseignez un chemin de fichier.")
        return Path(value.strip()).expanduser().resolve()

    async def _load_profile(self, _: Any) -> None:
        try:
            path = self._path(self.profile_path.value)
            config = await asyncio.to_thread(load_profile, path)
            self._set_profile(config)
            self.profile_message.value = f"Profil chargé : {path}"
            self.profile_message.color = GREEN
            self._log(self.profile_message.value)
        except Exception as exc:
            self.profile_message.value = str(exc)
            self.profile_message.color = RED
            self._error("Chargement du profil", exc)
        self._update()

    async def _save_profile(self, _: Any) -> None:
        try:
            config = self._config()
            path = self._path(self.profile_path.value)
            await asyncio.to_thread(path.parent.mkdir, parents=True, exist_ok=True)
            await asyncio.to_thread(save_profile, config, path)
            self.profile_message.value = f"Profil enregistré : {path}"
            self.profile_message.color = GREEN
            self._log(self.profile_message.value)
        except Exception as exc:
            self.profile_message.value = str(exc)
            self.profile_message.color = RED
            self._error("Enregistrement du profil", exc)
        self._update()

    async def _export(self, extension: str) -> None:
        try:
            waveform = simulate(self._config(), max_frames=4)
            path = self._path(self.export_path.value).with_suffix(extension)
            await asyncio.to_thread(path.parent.mkdir, parents=True, exist_ok=True)
            if extension == ".svg":
                await asyncio.to_thread(
                    path.write_text, waveform_svg(waveform, width=1600), encoding="utf-8"
                )
            elif extension == ".csv":
                await asyncio.to_thread(export_csv, waveform, path)
            else:
                await asyncio.to_thread(export_vcd, waveform, path)
            self.export_message.value = f"Export enregistré : {path}"
            if waveform.truncated:
                self.export_message.value += " · limité aux 4 premières trames"
            self.export_message.color = GREEN
            self._log(self.export_message.value)
        except Exception as exc:
            self.export_message.value = str(exc)
            self.export_message.color = RED
            self._error("Export du chronogramme", exc)
        self._update()

    async def _export_svg(self, _: Any) -> None:
        await self._export(".svg")

    async def _export_csv(self, _: Any) -> None:
        await self._export(".csv")

    async def _export_vcd(self, _: Any) -> None:
        await self._export(".vcd")

    def _toolchain(self) -> Toolchain:
        path = self._path(self.toolchain_path.value)
        return Toolchain(ToolchainConfig.from_json(path), self.project_root)

    def _worker_log(self, message: str) -> None:
        if self.loop is not None and not self.closing:
            self.loop.call_soon_threadsafe(self._queue_worker_log, str(message))

    def _queue_worker_log(self, message: str) -> None:
        if self.closing:
            return
        self.worker_messages.append(message)
        if self.log_flush_handle is None and self.loop is not None:
            # Synthesis can emit thousands of lines per second. Batch updates
            # rather than serializing the complete Flet control tree per line.
            self.log_flush_handle = self.loop.call_later(0.1, self._flush_worker_logs)

    def _flush_worker_logs(self) -> None:
        if self.log_flush_handle is not None:
            self.log_flush_handle.cancel()
            self.log_flush_handle = None
        if self.worker_messages:
            messages = "\n".join(self.worker_messages)
            self.worker_messages.clear()
            self._log(messages)

    async def _tool_action(self, title: str, action: Callable[[], Any]) -> Any:
        self.tool_pending = True
        self.tool_progress.visible = True
        self.tool_message.value = f"{title} en cours… Consultez le journal pour les détails."
        self.tool_message.color = AMBER
        self._buttons()
        self._update()
        try:
            result = await asyncio.to_thread(action)
            self._flush_worker_logs()
            self.tool_message.value = f"{title} : opération terminée."
            self.tool_message.color = GREEN
            self._log(self.tool_message.value, GREEN)
            return result
        except Exception as exc:
            self._flush_worker_logs()
            self.tool_message.value = f"{title} : {exc}"
            self.tool_message.color = RED
            self._error(title, exc)
            return None
        finally:
            self.tool_pending = False
            self.tool_progress.visible = False
            self._buttons()
            self._update()

    async def _doctor(self, _: Any) -> None:
        if self.tool_pending:
            return

        def run() -> Any:
            return self._toolchain().doctor()

        results = await self._tool_action("Vérification des outils", run)
        if results is not None:
            self.doctor_results.controls = []
            for result in results:
                if isinstance(result, dict):
                    name = str(result.get("name", "Outil"))
                    ok = bool(result.get("ok", False))
                    detail = str(result.get("detail", result.get("message", "")))
                else:
                    name = str(getattr(result, "name", "Outil"))
                    ok = bool(getattr(result, "ok", False))
                    detail = str(getattr(result, "detail", getattr(result, "message", result)))
                self.doctor_results.controls.append(
                    ft.Row(
                        [
                            ft.Icon(
                                ft.Icons.CHECK_CIRCLE if ok else ft.Icons.ERROR_OUTLINE,
                                color=GREEN if ok else RED,
                                size=18,
                            ),
                            ft.Text(
                                f"{name} · {detail}",
                                size=12,
                                color=MUTED,
                                selectable=True,
                                expand=True,
                            ),
                        ]
                    )
                )
                self._log(f"{name} · {'OK' if ok else 'INDISPONIBLE'} · {detail}")
            self._update()

    async def _build(self, _: Any) -> None:
        if self.tool_pending:
            return
        result = await self._tool_action(
            "Compilation FPGA",
            lambda: self._toolchain().build(log=self._worker_log),
        )
        if result is not None:
            self.bitstream_path.value = str(result)
            self.tool_message.value = f"Bitstream créé : {result}"
            self._update()

    async def _program(self, _: Any) -> None:
        if self.tool_pending or self.serial_pending:
            return
        try:
            bitstream = self._path(self.bitstream_path.value)
            if not bitstream.is_file():
                raise ValueError(
                    "Bitstream introuvable. Compilez ce projet pour produire "
                    "un bitstream validé, puis utilisez le fichier créé."
                )
        except Exception as exc:
            self._error("Programmation FPGA", exc)
            return
        # Reconfiguration resets the UART receiver. Closing the old session
        # avoids interpreting a stale response as the next command's reply.
        if isinstance(self.device, SerialDevice) and self.device.connected:
            await self._toggle_connection()

        def program() -> bool:
            self._toolchain().program(bitstream, log=self._worker_log)
            return True

        result = await self._tool_action("Programmation SRAM", program)
        if result is not None:
            self._log(
                "Le FPGA est configuré. Connectez le port UART dans Pilotage "
                "pour envoyer des trames.",
                BLUE,
            )

    async def _export_journal(self, _: Any) -> None:
        try:
            path = self._path(self.journal_path.value)
            await asyncio.to_thread(path.parent.mkdir, parents=True, exist_ok=True)
            await asyncio.to_thread(
                path.write_text, "\n".join(self.log_lines) + "\n", encoding="utf-8"
            )
            self._log(f"Journal enregistré : {path}", GREEN)
        except Exception as exc:
            self._error("Export du journal", exc)

    def _clear_journal(self, _: Any) -> None:
        self.log_lines.clear()
        self.journal.controls.clear()
        self._update()

    async def shutdown(self, _: Any = None) -> None:
        self.closing = True
        if self.log_flush_handle is not None:
            self.log_flush_handle.cancel()
            self.log_flush_handle = None
        if self.poll_task is not None:
            self.poll_task.cancel()
            try:
                await self.poll_task
            except asyncio.CancelledError:
                pass
        async with self.serial_lock:
            if self.device is not None:
                await asyncio.to_thread(self.device.close)
            self.device = None

    async def start(self) -> None:
        self.loop = asyncio.get_running_loop()
        self.page.on_disconnect = self.shutdown
        self.page.add(self.layout())
        self._changed()
        self._log("Arty Frame Studio · mode démo disponible sans carte et sans outils FPGA.", BLUE)
        await self._refresh_ports()
        await self._toggle_connection()
        self.poll_task = asyncio.create_task(self._poll())


async def main(page: ft.Page) -> None:
    page.title = "Arty Frame Studio · A7-100T"
    page.theme_mode = ft.ThemeMode.DARK
    page.theme = ft.Theme(color_scheme_seed=AMBER, font_family="Roboto")
    page.bgcolor = BG
    page.padding = 24
    page.window.width = 1220
    page.window.height = 930
    page.window.min_width = 760
    page.window.min_height = 680
    await Studio(page).start()


def run() -> None:
    """Console entry point for the desktop application."""
    ft.app(target=main)


if __name__ == "__main__":
    run()
