# Arty A7-100T xc7a100tcsg324-1, board revisions D/E.
# Digilent: https://github.com/Digilent/digilent-xdc/blob/master/Arty-A7-100-Master.xdc
# Generated by arty_frame_studio.firmware_config; edit the configuration,
# not this file. Only nextpnr-xilinx-supported commands are used.
# The second create_clock constrains the synthesized 200 MHz BUFG net.
# create_generated_clock is NOT implemented by this nextpnr XDC parser.
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk100]
create_clock -period 10.000 -name clk100 [get_ports clk100]
create_clock -period 5.000 -name core_clock [get_nets core_clock]

# ck_rst: red RESET button, active low (not the user push buttons).
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports reset_n]

# FT2232 USB-UART. Digilent names these from the PC (DTE) point of view:
# uart_txd_in (A9) is the PC transmit line, an FPGA INPUT; uart_rxd_out (D10)
# is the PC receive line, an FPGA OUTPUT. LiteX digilent_arty: tx=D10, rx=A9.
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports uart_rx]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports uart_tx]

# Outputs: DATA JB1 (E15), CLK JB2 (E16), LATCH JB3 (D15).
# Pmod pins 5/11 are ground, 6/12 are 3.3 V supply.
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 8} [get_ports data_out]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 8} [get_ports frame_clk]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33 SLEW FAST DRIVE 8} [get_ports latch_enable]

# Four monochrome LEDs LD4-LD7: locked, busy, reserved, completed (LSB first).
# A host LED command temporarily replaces them with its test pattern.
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
